openapi: 3.1.0
overlay: 1.0.0
info:
  title: Add MCP scopes
  version: 0.0.0
actions:
  # Add MCP scopes to all endpoints
  - target: $.paths.*["get","head","query"]
    update:
      x-speakeasy-mcp:
        scopes: [read]
        disabled: false
  
  - target: $.paths.*["post","put","delete","patch"]
    update:
      x-speakeasy-mcp:
        scopes: [write]
        disabled: false
  
  # # Disable depricated endpoints that should not be used by the MCP server
  # - target: $.paths["/groups/{group_id}/reviewers"].get
  #   update: 
  #     x-speakeasy-mcp:
  #       disabled: true
  # - target: $.paths["/groups/{group_id}/reviewers"].put
  #   update: 
  #     x-speakeasy-mcp:
  #       disabled: true
  # - target: $.paths["/groups/{group_id}/reviewer-stages"].get
  #   update: 
  #     x-speakeasy-mcp: 
  #       disabled: true
  # - target: $.paths["/groups/{group_id}/reviewer-stages"].put
  #   update: 
  #     x-speakeasy-mcp: 
  #       disabled: true
  
  # Disable endpoints that are not relevant for the MCP server
  # - target: $.paths["/sessions"].get
  #   update: 
  #     x-speakeasy-mcp:
  #       disabled: true