openapi: 3.1.0
overlay: 1.0.0
info:
  title: Add MCP scopes
  version: 0.0.0
actions:
  # Add MCP scopes to all endpoints
  - target: $.paths.*["get","head","query"]
    update:
      x-speakeasy-mcp:
        scopes: [read]
        disabled: false
  
  - target: $.paths.*["post","put","delete","patch"]
    update:
      x-speakeasy-mcp:
        scopes: [write]
        disabled: false
  
  # Add pagination configuration for cursor-based endpoints
  - target: $.paths["/bundles"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.bundles
          nextCursor: $.next
  
  - target: $.paths["/bundles/{bundle_id}/resources"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.bundle_resources
          nextCursor: $.next

  - target: $.paths["/bundles/{bundle_id}/groups"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.bundle_groups
          nextCursor: $.next

  - target: $.paths["/events"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/groups"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/group-bindings"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/owners"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/requests"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.requests
          nextCursor: $.cursor

  - target: $.paths["/resources"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/non-human-identities"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/users"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/tags"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next

  - target: $.paths["/uars"].get
    update:
      x-speakeasy-pagination:
        type: cursor
        inputs:
          - name: cursor
            in: parameters
            type: cursor
          - name: page_size
            in: parameters
            type: limit
        outputs:
          results: $.results
          nextCursor: $.next
