openapi: 3.1.0
overlay: 1.0.0
info:
  title: Update API documentation for MCP
  version: 0.0.0
actions:
    - target: $.paths['/user'].get
      update:
        description: |
          Retrieves detailed user information from Opal. This endpoint is designed to fetch user details by
          either user ID (UUID) or email address. The endpoint follows a strict precedence rule where
          user_id takes priority over email if both are provided.

          Key Implementation Notes:
          - Exactly one identifier (user_id OR email) must be provided
          - Returns a complete User object with all associated metadata
          - Suitable for user verification and profile data retrieval
          - Recommended for MCP user synchronization workflows

          Authentication:
          - Requires valid API authentication
          - Respects standard Opal authorization rules
    - target: $.components.schemas.User
      update:
        description: |
          # User Object

          ### Core Properties
          - `user_id`: Unique identifier (UUID v4) for the user
          - `email`: Primary email address, used for authentication and notifications
          - `full_name`: Display name, combining first_name and last_name
          - `position`: Organizational role or job title
          - `hr_idp_status`: Current provisioning status from HR/IDP system
          
          ### MCP Integration Guidelines
          1. User Synchronization:
            - Match users by `user_id` as primary key
            - Use email as secondary matching field
            - Maintain hr_idp_status for access control decisions
          2. Status Handling:
            - ACTIVE: Full system access granted
            - SUSPENDED: Temporary access restriction
            - DEPROVISIONED: Access removed but user record maintained
            - DELETED: User record marked for removal
            - NOT_FOUND: User doesn't exist in HR/IDP system
    - target: $.components.schemas.UserHrIdpStatusEnum
      update:
        description: |
            Represents the current status of a user as reported by the HR/IDP provider.

            ### Status Definitions
            - `ACTIVE`: User is currently employed and should have appropriate access
            - `SUSPENDED`: User access temporarily restricted (e.g., leave of absence)
            - `DEPROVISIONED`: User has been offboarded but record retained
            - `DELETED`: User record has been removed from HR system
            - `NOT_FOUND`: User doesn't exist in HR/IDP system

            ### MCP Status Handling
            ```typescript
            function handleUserStatusChange(user: User) {
              switch (user.hr_idp_status) {
                case 'ACTIVE':
                  return enableUserAccess(user.user_id);
                case 'SUSPENDED':
                  return suspendUserAccess(user.user_id);
                case 'DEPROVISIONED':
                case 'DELETED':
                  return revokeUserAccess(user.user_id);
                case 'NOT_FOUND':
                  return flagUserForReview(user.user_id);
              }
            }
            ```
    - target: $.paths["/user"]["get"]["parameters"][1]["description"]
      update: The email of the user. If both user ID and email are provided, user ID will take precedence. If neither are provided, an error will occur.
