/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accessRulesGetAccessRule } from "../../funcs/accessRulesGetAccessRule.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAccessRuleRequest$inboundSchema,
};

export const tool$accessRulesGetAccessRule: ToolDefinition<typeof args> = {
  name: "access-rules-get-access-rule",
  description:
    `Returns a list of access rule config given the group_id of the access rule.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accessRulesGetAccessRule(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
