/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsEndCampaign } from "../../funcs/campaignsEndCampaign.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EndCampaignRequest$inboundSchema,
};

export const tool$campaignsEndCampaign: ToolDefinition<typeof args> = {
  name: "campaigns-end-campaign",
  description: `End campaign

Ends a stopped campaign, setting \`ended_at\` and \`ended_by_user_id\`,
applying pending access changes, and queuing report generation.
Returns 400 unless the campaign is started and stopped and not already
ended.
`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await campaignsEndCampaign(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
