/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsStopCampaign } from "../../funcs/campaignsStopCampaign.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.StopCampaignRequest$inboundSchema,
};

export const tool$campaignsStopCampaign: ToolDefinition<typeof args> = {
  name: "campaigns-stop-campaign",
  description: `Stop campaign

Stops an ongoing campaign immediately, setting \`stopped_at\` and
\`stopped_by_user_id\`. Returns 400 if the campaign has not started or
has already stopped.
`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await campaignsStopCampaign(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
