/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsGetCampaignItems } from "../../funcs/campaignsGetCampaignItems.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCampaignItemsRequest$inboundSchema,
};

export const tool$campaignsGetCampaignItems: ToolDefinition<typeof args> = {
  name: "campaigns-get-campaign-items",
  description: `List campaign items

Returns a paginated list of review items for a campaign — the same rows
shown on the admin Reviews tab. Status is derived using the same rules
as the UI Status column. Soft-deleted role assignments are still
returned with \`is_target_deleted: true\`.
`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await campaignsGetCampaignItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
