/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsGetCampaign } from "../../funcs/campaignsGetCampaign.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCampaignRequest$inboundSchema,
};

export const tool$campaignsGetCampaign: ToolDefinition<typeof args> = {
  name: "campaigns-get-campaign",
  description: `Get campaign by ID

Returns a \`Campaign\` object.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await campaignsGetCampaign(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
