/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationTemplatesDeleteConfigurationTemplate } from "../../funcs/configurationTemplatesDeleteConfigurationTemplate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteConfigurationTemplateRequest$inboundSchema,
};

export const tool$configurationTemplatesDeleteConfigurationTemplate:
  ToolDefinition<typeof args> = {
    name: "configuration-templates-delete-configuration-template",
    description: `Deletes a configuration template.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await configurationTemplatesDeleteConfigurationTemplate(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
