/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsGetGroup } from "../../funcs/groupsGetGroup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetGroupRequest$inboundSchema,
};

export const tool$groupsGetGroup: ToolDefinition<typeof args> = {
  name: "groups-get-group",
  description: `Returns a \`Group\` object.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupsGetGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
