/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsGetGroupContainingGroups } from "../../funcs/groupsGetGroupContainingGroups.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetGroupContainingGroupsRequest$inboundSchema,
};

export const tool$groupsGetGroupContainingGroups: ToolDefinition<typeof args> =
  {
    name: "groups-get-group-containing-groups",
    description: `Gets the list of groups that the group gives access to.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await groupsGetGroupContainingGroups(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
