/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupBindingsCreateGroupBinding } from "../../funcs/groupBindingsCreateGroupBinding.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateGroupBindingInfo$inboundSchema,
};

export const tool$groupBindingsCreateGroupBinding: ToolDefinition<typeof args> =
  {
    name: "group-bindings-create-group-binding",
    description: `Creates a group binding.`,
    scopes: ["write"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await groupBindingsCreateGroupBinding(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
