/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsSetGroupMessageChannels } from "../../funcs/groupsSetGroupMessageChannels.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SetGroupMessageChannelsRequest$inboundSchema,
};

export const tool$groupsSetGroupMessageChannels: ToolDefinition<typeof args> = {
  name: "groups-set-group-message-channels",
  description: `Sets the list of audit message channels attached to a group.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupsSetGroupMessageChannels(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
