/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsSetGroupResources } from "../../funcs/groupsSetGroupResources.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SetGroupResourcesRequest$inboundSchema,
};

export const tool$groupsSetGroupResources: ToolDefinition<typeof args> = {
  name: "groups-set-group-resources",
  description: `Sets the list of resources that the group gives access to.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupsSetGroupResources(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
