/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupBindingsGetGroupBindings } from "../../funcs/groupBindingsGetGroupBindings.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetGroupBindingsRequest$inboundSchema,
};

export const tool$groupBindingsGetGroupBindings: ToolDefinition<typeof args> = {
  name: "group-bindings-get-group-bindings",
  description: `Returns a list of \`GroupBinding\` objects.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupBindingsGetGroupBindings(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
