/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { idpGroupMappingsUpdateIdpGroupMappings } from "../../funcs/idpGroupMappingsUpdateIdpGroupMappings.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateIdpGroupMappingsRequest$inboundSchema,
};

export const tool$idpGroupMappingsUpdateIdpGroupMappings: ToolDefinition<
  typeof args
> = {
  name: "idp-group-mappings-update-idp-group-mappings",
  description:
    `Updates the list of available \`IdpGroupMapping\` objects for an Okta app.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await idpGroupMappingsUpdateIdpGroupMappings(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
