/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messageChannelsGetMessageChannel } from "../../funcs/messageChannelsGetMessageChannel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMessageChannelRequest$inboundSchema,
};

export const tool$messageChannelsGetMessageChannel: ToolDefinition<
  typeof args
> = {
  name: "message-channels-get-message-channel",
  description: `Gets a \`MessageChannel\` object.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messageChannelsGetMessageChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
