/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { onCallSchedulesCreateOnCallSchedule } from "../../funcs/onCallSchedulesCreateOnCallSchedule.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateOnCallScheduleInfo$inboundSchema,
};

export const tool$onCallSchedulesCreateOnCallSchedule: ToolDefinition<
  typeof args
> = {
  name: "on-call-schedules-create-on-call-schedule",
  description: `Creates a \`OnCallSchedule\` objects.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await onCallSchedulesCreateOnCallSchedule(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
