/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { opalScriptsUpdateOpalScript } from "../../funcs/opalScriptsUpdateOpalScript.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateOpalScriptRequest$inboundSchema,
};

export const tool$opalScriptsUpdateOpalScript: ToolDefinition<typeof args> = {
  name: "opal-scripts-update-opal-script",
  description: `Update OpalScript

Updates an \`OpalScript\` object.`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await opalScriptsUpdateOpalScript(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
