/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { opalQueriesRunOpalQuery } from "../../funcs/opalQueriesRunOpalQuery.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.RunOpalQueryRequest$inboundSchema,
};

export const tool$opalQueriesRunOpalQuery: ToolDefinition<typeof args> = {
  name: "opal-queries-run-opal-query",
  description: `Run an ad-hoc OpalQuery

Executes an ad-hoc OpalQuery and returns paginated results. Two query types are supported: a **Node** query filters and returns entities (users, resources, or groups); an **Access** query returns the access grants between principals and their entitlements, one per (principal, entitlement, access level). Set \`type\` to \`NODE\` or \`ACCESS\` in the request body to select the query type.

This endpoint is available to OpalQuery beta participants. To request access, contact Opal support.
`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await opalQueriesRunOpalQuery(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
