/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { opalScriptsGetOpalScripts } from "../../funcs/opalScriptsGetOpalScripts.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$opalScriptsGetOpalScripts: ToolDefinition = {
  name: "opal-scripts-get-opal-scripts",
  description: `List OpalScripts

Returns the \`OpalScript\` objects in the caller's organization.`,
  scopes: ["read"],
  tool: async (client, ctx) => {
    const [result, apiCall] = await opalScriptsGetOpalScripts(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
