/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paladinUpdatePaladin } from "../../funcs/paladinUpdatePaladin.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdatePaladinRequest$inboundSchema,
};

export const tool$paladinUpdatePaladin: ToolDefinition<typeof args> = {
  name: "paladin-update-paladin",
  description: `Update Paladin

Updates a \`Paladin\` object.`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paladinUpdatePaladin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
