/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetResourceNhis } from "../../funcs/resourcesGetResourceNhis.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourceNhisRequest$inboundSchema,
};

export const tool$resourcesGetResourceNhis: ToolDefinition<typeof args> = {
  name: "resources-get-resource-nhis",
  description:
    `Gets the list of non-human identities with access to this resource.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesGetResourceNhis(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
