/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetResourceReviewers } from "../../funcs/resourcesGetResourceReviewers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourceReviewersRequest$inboundSchema,
};

export const tool$resourcesGetResourceReviewers: ToolDefinition<typeof args> = {
  name: "resources-get-resource-reviewers",
  description: `Gets the list of owner IDs of the reviewers for a resource.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesGetResourceReviewers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
