/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetResourceTags } from "../../funcs/resourcesGetResourceTags.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourceTagsRequest$inboundSchema,
};

export const tool$resourcesGetResourceTags: ToolDefinition<typeof args> = {
  name: "resources-get-resource-tags",
  description: `Returns all tags applied to the resource.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesGetResourceTags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
