/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetResourceGroups } from "../../funcs/resourcesGetResourceGroups.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourceGroupsRequest$inboundSchema,
};

export const tool$resourcesGetResourceGroups: ToolDefinition<typeof args> = {
  name: "resources-get-resource-groups",
  description: `Returns a list of groups that grant access to the resource`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesGetResourceGroups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
