/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensGetTokens } from "../../funcs/tokensGetTokens.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTokensRequest$inboundSchema,
};

export const tool$tokensGetTokens: ToolDefinition<typeof args> = {
  name: "tokens-get-tokens",
  description: `Get tokens

Returns a list of first-party API tokens for your organization. Requires admin access.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tokensGetTokens(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
