/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uarsGetUARs } from "../../funcs/uarsGetUARs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetUARsRequest$inboundSchema,
};

export const tool$uarsGetUARs: ToolDefinition<typeof args> = {
  name: "uars-get-UA-rs",
  description: `Returns a list of \`UAR\` objects.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uarsGetUARs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
