/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsEvents } from "../funcs/eventsEvents.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * Returns a list of `Event` objects.
   */
  async events(
    request: operations.EventsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedEventList> {
    return unwrapAsync(eventsEvents(
      this,
      request,
      options,
    ));
  }
}
