/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nonHumanIdentitiesGetNhis } from "../funcs/nonHumanIdentitiesGetNhis.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class NonHumanIdentities extends ClientSDK {
  /**
   * Returns a list of non-human identities for your organization.
   */
  async getNhis(
    request: operations.GetNhisRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetNhisResponse, { cursor: string }>> {
    return unwrapResultIterator(nonHumanIdentitiesGetNhis(
      this,
      request,
      options,
    ));
  }
}
