/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { opalQueriesRunOpalQuery } from "../funcs/opalQueriesRunOpalQuery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OpalQueries extends ClientSDK {
  /**
   * Run an ad-hoc OpalQuery
   *
   * @remarks
   * Executes an ad-hoc OpalQuery and returns paginated results. Two query types are supported: a **Node** query filters and returns entities (users, resources, or groups); an **Access** query returns the access grants between principals and their entitlements, one per (principal, entitlement, access level). Set `type` to `NODE` or `ACCESS` in the request body to select the query type.
   *
   * This endpoint is available to OpalQuery beta participants. To request access, contact Opal support.
   */
  async runOpalQuery(
    request: components.RunOpalQueryRequest,
    options?: RequestOptions,
  ): Promise<components.OpalQueryResults> {
    return unwrapAsync(opalQueriesRunOpalQuery(
      this,
      request,
      options,
    ));
  }
}
