workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Opal API:
        inputs:
            - location: https://app.opal.dev/openapi.yaml
        overlays:
            - location: mcp-scopes-and-endpoints-overlay.yaml
            - location: mcp-field-visibility-overlay.yaml
            - location: mcp-documentation-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/opal/opal/opal-api
targets:
    opal-mcp:
        target: typescript
        source: Opal API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/opal/opal/opal-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
