/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateResourceCustomAccessLevelRequest = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
  createResourceCustomAccessLevelInfo:
    components.CreateResourceCustomAccessLevelInfo;
};

/** @internal */
export const CreateResourceCustomAccessLevelRequest$inboundSchema: z.ZodType<
  CreateResourceCustomAccessLevelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
  CreateResourceCustomAccessLevelInfo:
    components.CreateResourceCustomAccessLevelInfo$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
    "CreateResourceCustomAccessLevelInfo":
      "createResourceCustomAccessLevelInfo",
  });
});
/** @internal */
export type CreateResourceCustomAccessLevelRequest$Outbound = {
  resource_id: string;
  CreateResourceCustomAccessLevelInfo:
    components.CreateResourceCustomAccessLevelInfo$Outbound;
};

/** @internal */
export const CreateResourceCustomAccessLevelRequest$outboundSchema: z.ZodType<
  CreateResourceCustomAccessLevelRequest$Outbound,
  z.ZodTypeDef,
  CreateResourceCustomAccessLevelRequest
> = z.object({
  resourceId: z.string(),
  createResourceCustomAccessLevelInfo:
    components.CreateResourceCustomAccessLevelInfo$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
    createResourceCustomAccessLevelInfo: "CreateResourceCustomAccessLevelInfo",
  });
});

export function createResourceCustomAccessLevelRequestToJSON(
  createResourceCustomAccessLevelRequest:
    CreateResourceCustomAccessLevelRequest,
): string {
  return JSON.stringify(
    CreateResourceCustomAccessLevelRequest$outboundSchema.parse(
      createResourceCustomAccessLevelRequest,
    ),
  );
}
export function createResourceCustomAccessLevelRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateResourceCustomAccessLevelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateResourceCustomAccessLevelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResourceCustomAccessLevelRequest' from JSON`,
  );
}
