/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTokenRequest = {
  /**
   * The ID of the token to delete.
   */
  tokenId: string;
};

/** @internal */
export const DeleteTokenRequest$inboundSchema: z.ZodType<
  DeleteTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "token_id": "tokenId",
  });
});
/** @internal */
export type DeleteTokenRequest$Outbound = {
  token_id: string;
};

/** @internal */
export const DeleteTokenRequest$outboundSchema: z.ZodType<
  DeleteTokenRequest$Outbound,
  z.ZodTypeDef,
  DeleteTokenRequest
> = z.object({
  tokenId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tokenId: "token_id",
  });
});

export function deleteTokenRequestToJSON(
  deleteTokenRequest: DeleteTokenRequest,
): string {
  return JSON.stringify(
    DeleteTokenRequest$outboundSchema.parse(deleteTokenRequest),
  );
}
export function deleteTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTokenRequest' from JSON`,
  );
}
