/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTagByIDRequest = {
  /**
   * The tag ID
   */
  tagId: string;
};

/** @internal */
export const DeleteTagByIDRequest$inboundSchema: z.ZodType<
  DeleteTagByIDRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tag_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tag_id": "tagId",
  });
});
/** @internal */
export type DeleteTagByIDRequest$Outbound = {
  tag_id: string;
};

/** @internal */
export const DeleteTagByIDRequest$outboundSchema: z.ZodType<
  DeleteTagByIDRequest$Outbound,
  z.ZodTypeDef,
  DeleteTagByIDRequest
> = z.object({
  tagId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tagId: "tag_id",
  });
});

export function deleteTagByIDRequestToJSON(
  deleteTagByIDRequest: DeleteTagByIDRequest,
): string {
  return JSON.stringify(
    DeleteTagByIDRequest$outboundSchema.parse(deleteTagByIDRequest),
  );
}
export function deleteTagByIDRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTagByIDRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTagByIDRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTagByIDRequest' from JSON`,
  );
}
