/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePaladinContextSourceRequest = {
  /**
   * The ID of the Paladin.
   */
  paladinId: string;
  /**
   * The ID of the context source.
   */
  contextSourceId: string;
};

/** @internal */
export const DeletePaladinContextSourceRequest$inboundSchema: z.ZodType<
  DeletePaladinContextSourceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  paladin_id: z.string(),
  context_source_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "paladin_id": "paladinId",
    "context_source_id": "contextSourceId",
  });
});
/** @internal */
export type DeletePaladinContextSourceRequest$Outbound = {
  paladin_id: string;
  context_source_id: string;
};

/** @internal */
export const DeletePaladinContextSourceRequest$outboundSchema: z.ZodType<
  DeletePaladinContextSourceRequest$Outbound,
  z.ZodTypeDef,
  DeletePaladinContextSourceRequest
> = z.object({
  paladinId: z.string(),
  contextSourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    paladinId: "paladin_id",
    contextSourceId: "context_source_id",
  });
});

export function deletePaladinContextSourceRequestToJSON(
  deletePaladinContextSourceRequest: DeletePaladinContextSourceRequest,
): string {
  return JSON.stringify(
    DeletePaladinContextSourceRequest$outboundSchema.parse(
      deletePaladinContextSourceRequest,
    ),
  );
}
export function deletePaladinContextSourceRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeletePaladinContextSourceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePaladinContextSourceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePaladinContextSourceRequest' from JSON`,
  );
}
