/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteResourceNhiRequest = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
  /**
   * The resource ID of the non-human identity to remove from this resource.
   */
  nonHumanIdentityId: string;
  /**
   * The remote ID of the access level for which this non-human identity has direct access. If omitted, the default access level remote ID value (empty string) is assumed.
   */
  accessLevelRemoteId?: string | undefined;
};

/** @internal */
export const DeleteResourceNhiRequest$inboundSchema: z.ZodType<
  DeleteResourceNhiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
  non_human_identity_id: z.string(),
  access_level_remote_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
    "non_human_identity_id": "nonHumanIdentityId",
    "access_level_remote_id": "accessLevelRemoteId",
  });
});

/** @internal */
export type DeleteResourceNhiRequest$Outbound = {
  resource_id: string;
  non_human_identity_id: string;
  access_level_remote_id?: string | undefined;
};

/** @internal */
export const DeleteResourceNhiRequest$outboundSchema: z.ZodType<
  DeleteResourceNhiRequest$Outbound,
  z.ZodTypeDef,
  DeleteResourceNhiRequest
> = z.object({
  resourceId: z.string(),
  nonHumanIdentityId: z.string(),
  accessLevelRemoteId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
    nonHumanIdentityId: "non_human_identity_id",
    accessLevelRemoteId: "access_level_remote_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteResourceNhiRequest$ {
  /** @deprecated use `DeleteResourceNhiRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteResourceNhiRequest$inboundSchema;
  /** @deprecated use `DeleteResourceNhiRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteResourceNhiRequest$outboundSchema;
  /** @deprecated use `DeleteResourceNhiRequest$Outbound` instead. */
  export type Outbound = DeleteResourceNhiRequest$Outbound;
}

export function deleteResourceNhiRequestToJSON(
  deleteResourceNhiRequest: DeleteResourceNhiRequest,
): string {
  return JSON.stringify(
    DeleteResourceNhiRequest$outboundSchema.parse(deleteResourceNhiRequest),
  );
}

export function deleteResourceNhiRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResourceNhiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResourceNhiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResourceNhiRequest' from JSON`,
  );
}
