/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAppRequest = {
  /**
   * The ID of the app.
   */
  appId: string;
};

/** @internal */
export const GetAppRequest$inboundSchema: z.ZodType<
  GetAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
  });
});
/** @internal */
export type GetAppRequest$Outbound = {
  app_id: string;
};

/** @internal */
export const GetAppRequest$outboundSchema: z.ZodType<
  GetAppRequest$Outbound,
  z.ZodTypeDef,
  GetAppRequest
> = z.object({
  appId: z.string(),
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
  });
});

export function getAppRequestToJSON(getAppRequest: GetAppRequest): string {
  return JSON.stringify(GetAppRequest$outboundSchema.parse(getAppRequest));
}
export function getAppRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAppRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAppRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppRequest' from JSON`,
  );
}
