/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCampaignItemsRequest = {
  /**
   * The ID of the campaign.
   */
  campaignId: string;
  /**
   * The pagination cursor value.
   */
  cursor?: string | undefined;
  /**
   * Number of results to return per page. Default is 200; maximum is
   *
   * @remarks
   * 500 (the campaign-items list cap).
   */
  pageSize?: number | undefined;
  /**
   * Filter by derived item status. When multiple values are provided,
   *
   * @remarks
   * items matching any status are returned (OR).
   */
  statuses?: Array<components.CampaignItemStatusEnum> | undefined;
  /**
   * Restrict to items assigned to this reviewer user ID.
   */
  reviewerUserId?: string | undefined;
  /**
   * When true, restrict to items with no reviewer assigned.
   */
  unassigned?: boolean | undefined;
  /**
   * Case-insensitive search over principal name, asset name, and
   *
   * @remarks
   * reviewer name.
   */
  search?: string | undefined;
};

/** @internal */
export const GetCampaignItemsRequest$inboundSchema: z.ZodType<
  GetCampaignItemsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  campaign_id: z.string(),
  cursor: z.string().optional(),
  page_size: z.number().int().optional(),
  statuses: z.array(components.CampaignItemStatusEnum$inboundSchema).optional(),
  reviewer_user_id: z.string().optional(),
  unassigned: z.boolean().optional(),
  search: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "campaign_id": "campaignId",
    "page_size": "pageSize",
    "reviewer_user_id": "reviewerUserId",
  });
});
/** @internal */
export type GetCampaignItemsRequest$Outbound = {
  campaign_id: string;
  cursor?: string | undefined;
  page_size?: number | undefined;
  statuses?: Array<string> | undefined;
  reviewer_user_id?: string | undefined;
  unassigned?: boolean | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetCampaignItemsRequest$outboundSchema: z.ZodType<
  GetCampaignItemsRequest$Outbound,
  z.ZodTypeDef,
  GetCampaignItemsRequest
> = z.object({
  campaignId: z.string(),
  cursor: z.string().optional(),
  pageSize: z.number().int().optional(),
  statuses: z.array(components.CampaignItemStatusEnum$outboundSchema)
    .optional(),
  reviewerUserId: z.string().optional(),
  unassigned: z.boolean().optional(),
  search: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    campaignId: "campaign_id",
    pageSize: "page_size",
    reviewerUserId: "reviewer_user_id",
  });
});

export function getCampaignItemsRequestToJSON(
  getCampaignItemsRequest: GetCampaignItemsRequest,
): string {
  return JSON.stringify(
    GetCampaignItemsRequest$outboundSchema.parse(getCampaignItemsRequest),
  );
}
export function getCampaignItemsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCampaignItemsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCampaignItemsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCampaignItemsRequest' from JSON`,
  );
}
