/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetGroupUsersRequest = {
  /**
   * The ID of the group.
   */
  groupId: string;
};

/** @internal */
export const GetGroupUsersRequest$inboundSchema: z.ZodType<
  GetGroupUsersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  group_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "group_id": "groupId",
  });
});

/** @internal */
export type GetGroupUsersRequest$Outbound = {
  group_id: string;
};

/** @internal */
export const GetGroupUsersRequest$outboundSchema: z.ZodType<
  GetGroupUsersRequest$Outbound,
  z.ZodTypeDef,
  GetGroupUsersRequest
> = z.object({
  groupId: z.string(),
}).transform((v) => {
  return remap$(v, {
    groupId: "group_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetGroupUsersRequest$ {
  /** @deprecated use `GetGroupUsersRequest$inboundSchema` instead. */
  export const inboundSchema = GetGroupUsersRequest$inboundSchema;
  /** @deprecated use `GetGroupUsersRequest$outboundSchema` instead. */
  export const outboundSchema = GetGroupUsersRequest$outboundSchema;
  /** @deprecated use `GetGroupUsersRequest$Outbound` instead. */
  export type Outbound = GetGroupUsersRequest$Outbound;
}

export function getGroupUsersRequestToJSON(
  getGroupUsersRequest: GetGroupUsersRequest,
): string {
  return JSON.stringify(
    GetGroupUsersRequest$outboundSchema.parse(getGroupUsersRequest),
  );
}

export function getGroupUsersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetGroupUsersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGroupUsersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGroupUsersRequest' from JSON`,
  );
}
