/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetGroupContainingGroupsRequest = {
  /**
   * The ID of the group.
   */
  groupId: string;
  /**
   * The access level's remote ID to filter by.
   */
  accessLevelRemoteId?: string | undefined;
};

/** @internal */
export const GetGroupContainingGroupsRequest$inboundSchema: z.ZodType<
  GetGroupContainingGroupsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  group_id: z.string(),
  access_level_remote_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "group_id": "groupId",
    "access_level_remote_id": "accessLevelRemoteId",
  });
});
/** @internal */
export type GetGroupContainingGroupsRequest$Outbound = {
  group_id: string;
  access_level_remote_id?: string | undefined;
};

/** @internal */
export const GetGroupContainingGroupsRequest$outboundSchema: z.ZodType<
  GetGroupContainingGroupsRequest$Outbound,
  z.ZodTypeDef,
  GetGroupContainingGroupsRequest
> = z.object({
  groupId: z.string(),
  accessLevelRemoteId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    groupId: "group_id",
    accessLevelRemoteId: "access_level_remote_id",
  });
});

export function getGroupContainingGroupsRequestToJSON(
  getGroupContainingGroupsRequest: GetGroupContainingGroupsRequest,
): string {
  return JSON.stringify(
    GetGroupContainingGroupsRequest$outboundSchema.parse(
      getGroupContainingGroupsRequest,
    ),
  );
}
export function getGroupContainingGroupsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetGroupContainingGroupsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGroupContainingGroupsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGroupContainingGroupsRequest' from JSON`,
  );
}
