/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOpalScriptFromNameRequest = {
  /**
   * The name of the OpalScript.
   */
  opalScriptName: string;
};

/** @internal */
export const GetOpalScriptFromNameRequest$inboundSchema: z.ZodType<
  GetOpalScriptFromNameRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  opal_script_name: z.string(),
}).transform((v) => {
  return remap$(v, {
    "opal_script_name": "opalScriptName",
  });
});
/** @internal */
export type GetOpalScriptFromNameRequest$Outbound = {
  opal_script_name: string;
};

/** @internal */
export const GetOpalScriptFromNameRequest$outboundSchema: z.ZodType<
  GetOpalScriptFromNameRequest$Outbound,
  z.ZodTypeDef,
  GetOpalScriptFromNameRequest
> = z.object({
  opalScriptName: z.string(),
}).transform((v) => {
  return remap$(v, {
    opalScriptName: "opal_script_name",
  });
});

export function getOpalScriptFromNameRequestToJSON(
  getOpalScriptFromNameRequest: GetOpalScriptFromNameRequest,
): string {
  return JSON.stringify(
    GetOpalScriptFromNameRequest$outboundSchema.parse(
      getOpalScriptFromNameRequest,
    ),
  );
}
export function getOpalScriptFromNameRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOpalScriptFromNameRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpalScriptFromNameRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpalScriptFromNameRequest' from JSON`,
  );
}
