/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetResourceMessageChannelsRequest = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
};

/** @internal */
export const GetResourceMessageChannelsRequest$inboundSchema: z.ZodType<
  GetResourceMessageChannelsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
  });
});

/** @internal */
export type GetResourceMessageChannelsRequest$Outbound = {
  resource_id: string;
};

/** @internal */
export const GetResourceMessageChannelsRequest$outboundSchema: z.ZodType<
  GetResourceMessageChannelsRequest$Outbound,
  z.ZodTypeDef,
  GetResourceMessageChannelsRequest
> = z.object({
  resourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetResourceMessageChannelsRequest$ {
  /** @deprecated use `GetResourceMessageChannelsRequest$inboundSchema` instead. */
  export const inboundSchema = GetResourceMessageChannelsRequest$inboundSchema;
  /** @deprecated use `GetResourceMessageChannelsRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetResourceMessageChannelsRequest$outboundSchema;
  /** @deprecated use `GetResourceMessageChannelsRequest$Outbound` instead. */
  export type Outbound = GetResourceMessageChannelsRequest$Outbound;
}

export function getResourceMessageChannelsRequestToJSON(
  getResourceMessageChannelsRequest: GetResourceMessageChannelsRequest,
): string {
  return JSON.stringify(
    GetResourceMessageChannelsRequest$outboundSchema.parse(
      getResourceMessageChannelsRequest,
    ),
  );
}

export function getResourceMessageChannelsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResourceMessageChannelsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourceMessageChannelsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourceMessageChannelsRequest' from JSON`,
  );
}
