/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetResourceTagsRequest = {
  /**
   * The ID of the resource whose tags to return.
   */
  resourceId: string;
};

/** @internal */
export const GetResourceTagsRequest$inboundSchema: z.ZodType<
  GetResourceTagsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
  });
});

/** @internal */
export type GetResourceTagsRequest$Outbound = {
  resource_id: string;
};

/** @internal */
export const GetResourceTagsRequest$outboundSchema: z.ZodType<
  GetResourceTagsRequest$Outbound,
  z.ZodTypeDef,
  GetResourceTagsRequest
> = z.object({
  resourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetResourceTagsRequest$ {
  /** @deprecated use `GetResourceTagsRequest$inboundSchema` instead. */
  export const inboundSchema = GetResourceTagsRequest$inboundSchema;
  /** @deprecated use `GetResourceTagsRequest$outboundSchema` instead. */
  export const outboundSchema = GetResourceTagsRequest$outboundSchema;
  /** @deprecated use `GetResourceTagsRequest$Outbound` instead. */
  export type Outbound = GetResourceTagsRequest$Outbound;
}

export function getResourceTagsRequestToJSON(
  getResourceTagsRequest: GetResourceTagsRequest,
): string {
  return JSON.stringify(
    GetResourceTagsRequest$outboundSchema.parse(getResourceTagsRequest),
  );
}

export function getResourceTagsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResourceTagsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourceTagsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourceTagsRequest' from JSON`,
  );
}
