/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRequestCommentsRequest = {
  /**
   * The ID of the request to get comments for
   */
  id: string;
};

/** @internal */
export const GetRequestCommentsRequest$inboundSchema: z.ZodType<
  GetRequestCommentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetRequestCommentsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetRequestCommentsRequest$outboundSchema: z.ZodType<
  GetRequestCommentsRequest$Outbound,
  z.ZodTypeDef,
  GetRequestCommentsRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRequestCommentsRequest$ {
  /** @deprecated use `GetRequestCommentsRequest$inboundSchema` instead. */
  export const inboundSchema = GetRequestCommentsRequest$inboundSchema;
  /** @deprecated use `GetRequestCommentsRequest$outboundSchema` instead. */
  export const outboundSchema = GetRequestCommentsRequest$outboundSchema;
  /** @deprecated use `GetRequestCommentsRequest$Outbound` instead. */
  export type Outbound = GetRequestCommentsRequest$Outbound;
}

export function getRequestCommentsRequestToJSON(
  getRequestCommentsRequest: GetRequestCommentsRequest,
): string {
  return JSON.stringify(
    GetRequestCommentsRequest$outboundSchema.parse(getRequestCommentsRequest),
  );
}

export function getRequestCommentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRequestCommentsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRequestCommentsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRequestCommentsRequest' from JSON`,
  );
}
