/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetResourceScopedRolePermissionsRequest = {
  /**
   * The ID of the resource whose scoped role permissions belong to.
   */
  resourceId: string;
};

/** @internal */
export const GetResourceScopedRolePermissionsRequest$inboundSchema: z.ZodType<
  GetResourceScopedRolePermissionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
  });
});

/** @internal */
export type GetResourceScopedRolePermissionsRequest$Outbound = {
  resource_id: string;
};

/** @internal */
export const GetResourceScopedRolePermissionsRequest$outboundSchema: z.ZodType<
  GetResourceScopedRolePermissionsRequest$Outbound,
  z.ZodTypeDef,
  GetResourceScopedRolePermissionsRequest
> = z.object({
  resourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetResourceScopedRolePermissionsRequest$ {
  /** @deprecated use `GetResourceScopedRolePermissionsRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetResourceScopedRolePermissionsRequest$inboundSchema;
  /** @deprecated use `GetResourceScopedRolePermissionsRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetResourceScopedRolePermissionsRequest$outboundSchema;
  /** @deprecated use `GetResourceScopedRolePermissionsRequest$Outbound` instead. */
  export type Outbound = GetResourceScopedRolePermissionsRequest$Outbound;
}

export function getResourceScopedRolePermissionsRequestToJSON(
  getResourceScopedRolePermissionsRequest:
    GetResourceScopedRolePermissionsRequest,
): string {
  return JSON.stringify(
    GetResourceScopedRolePermissionsRequest$outboundSchema.parse(
      getResourceScopedRolePermissionsRequest,
    ),
  );
}

export function getResourceScopedRolePermissionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetResourceScopedRolePermissionsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetResourceScopedRolePermissionsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetResourceScopedRolePermissionsRequest' from JSON`,
  );
}
