/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetResourceAccessLevelsRequest = {
  /**
   * The ID of the resource whose access levels to return.
   */
  resourceId: string;
};

/** @internal */
export const GetResourceAccessLevelsRequest$inboundSchema: z.ZodType<
  GetResourceAccessLevelsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
  });
});
/** @internal */
export type GetResourceAccessLevelsRequest$Outbound = {
  resource_id: string;
};

/** @internal */
export const GetResourceAccessLevelsRequest$outboundSchema: z.ZodType<
  GetResourceAccessLevelsRequest$Outbound,
  z.ZodTypeDef,
  GetResourceAccessLevelsRequest
> = z.object({
  resourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
  });
});

export function getResourceAccessLevelsRequestToJSON(
  getResourceAccessLevelsRequest: GetResourceAccessLevelsRequest,
): string {
  return JSON.stringify(
    GetResourceAccessLevelsRequest$outboundSchema.parse(
      getResourceAccessLevelsRequest,
    ),
  );
}
export function getResourceAccessLevelsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResourceAccessLevelsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourceAccessLevelsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourceAccessLevelsRequest' from JSON`,
  );
}
