/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTokensRequest = {
  /**
   * The pagination cursor value.
   */
  cursor?: string | undefined;
  /**
   * Number of results to return per page. Default is 200.
   */
  pageSize?: number | undefined;
  /**
   * Filter by token IDs.
   */
  tokenIds?: Array<string> | undefined;
  /**
   * Filter by user ID.
   */
  userId?: string | undefined;
};

/** @internal */
export const GetTokensRequest$inboundSchema: z.ZodType<
  GetTokensRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().optional(),
  token_ids: z.array(z.string()).optional(),
  user_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "token_ids": "tokenIds",
    "user_id": "userId",
  });
});
/** @internal */
export type GetTokensRequest$Outbound = {
  cursor?: string | undefined;
  page_size?: number | undefined;
  token_ids?: Array<string> | undefined;
  user_id?: string | undefined;
};

/** @internal */
export const GetTokensRequest$outboundSchema: z.ZodType<
  GetTokensRequest$Outbound,
  z.ZodTypeDef,
  GetTokensRequest
> = z.object({
  cursor: z.string().optional(),
  pageSize: z.number().int().optional(),
  tokenIds: z.array(z.string()).optional(),
  userId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    tokenIds: "token_ids",
    userId: "user_id",
  });
});

export function getTokensRequestToJSON(
  getTokensRequest: GetTokensRequest,
): string {
  return JSON.stringify(
    GetTokensRequest$outboundSchema.parse(getTokensRequest),
  );
}
export function getTokensRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTokensRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTokensRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTokensRequest' from JSON`,
  );
}
