/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUARsRequest = {
  /**
   * The pagination cursor value.
   */
  cursor?: string | undefined;
  /**
   * Number of results to return per page. Default is 200.
   */
  pageSize?: number | undefined;
};

export type GetUARsResponse = {
  result: components.PaginatedUARsList;
};

/** @internal */
export const GetUARsRequest$inboundSchema: z.ZodType<
  GetUARsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
  });
});
/** @internal */
export type GetUARsRequest$Outbound = {
  cursor?: string | undefined;
  page_size?: number | undefined;
};

/** @internal */
export const GetUARsRequest$outboundSchema: z.ZodType<
  GetUARsRequest$Outbound,
  z.ZodTypeDef,
  GetUARsRequest
> = z.object({
  cursor: z.string().optional(),
  pageSize: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function getUARsRequestToJSON(getUARsRequest: GetUARsRequest): string {
  return JSON.stringify(GetUARsRequest$outboundSchema.parse(getUARsRequest));
}
export function getUARsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUARsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUARsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUARsRequest' from JSON`,
  );
}

/** @internal */
export const GetUARsResponse$inboundSchema: z.ZodType<
  GetUARsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.PaginatedUARsList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetUARsResponse$Outbound = {
  Result: components.PaginatedUARsList$Outbound;
};

/** @internal */
export const GetUARsResponse$outboundSchema: z.ZodType<
  GetUARsResponse$Outbound,
  z.ZodTypeDef,
  GetUARsResponse
> = z.object({
  result: components.PaginatedUARsList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getUARsResponseToJSON(
  getUARsResponse: GetUARsResponse,
): string {
  return JSON.stringify(GetUARsResponse$outboundSchema.parse(getUARsResponse));
}
export function getUARsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUARsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUARsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUARsResponse' from JSON`,
  );
}
