/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserGroupsRequest = {
  /**
   * The ID of the user whose groups to return.
   */
  userId: string;
  /**
   * The pagination cursor value.
   */
  cursor?: string | undefined;
  /**
   * Number of results to return per page. Default is 200.
   */
  pageSize?: number | undefined;
};

/** @internal */
export const GetUserGroupsRequest$inboundSchema: z.ZodType<
  GetUserGroupsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  cursor: z.string().optional(),
  page_size: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "page_size": "pageSize",
  });
});
/** @internal */
export type GetUserGroupsRequest$Outbound = {
  user_id: string;
  cursor?: string | undefined;
  page_size?: number | undefined;
};

/** @internal */
export const GetUserGroupsRequest$outboundSchema: z.ZodType<
  GetUserGroupsRequest$Outbound,
  z.ZodTypeDef,
  GetUserGroupsRequest
> = z.object({
  userId: z.string(),
  cursor: z.string().optional(),
  pageSize: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
    pageSize: "page_size",
  });
});

export function getUserGroupsRequestToJSON(
  getUserGroupsRequest: GetUserGroupsRequest,
): string {
  return JSON.stringify(
    GetUserGroupsRequest$outboundSchema.parse(getUserGroupsRequest),
  );
}
export function getUserGroupsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserGroupsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserGroupsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserGroupsRequest' from JSON`,
  );
}
