/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserTagsRequest = {
  /**
   * The ID of the user whose tags to return.
   */
  userId: string;
};

/** @internal */
export const GetUserTagsRequest$inboundSchema: z.ZodType<
  GetUserTagsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
  });
});
/** @internal */
export type GetUserTagsRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const GetUserTagsRequest$outboundSchema: z.ZodType<
  GetUserTagsRequest$Outbound,
  z.ZodTypeDef,
  GetUserTagsRequest
> = z.object({
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function getUserTagsRequestToJSON(
  getUserTagsRequest: GetUserTagsRequest,
): string {
  return JSON.stringify(
    GetUserTagsRequest$outboundSchema.parse(getUserTagsRequest),
  );
}
export function getUserTagsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserTagsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserTagsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserTagsRequest' from JSON`,
  );
}
