/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemindRequestReviewerRequest = {
  /**
   * The ID of the request whose reviewer should be reminded.
   */
  id: string;
  /**
   * The ID of the pending reviewer to remind.
   */
  reviewerId: string;
};

/**
 * The reminder was sent, or the request was already resolved.
 */
export type RemindRequestReviewerResponse = {
  success: boolean;
};

/** @internal */
export const RemindRequestReviewerRequest$inboundSchema: z.ZodType<
  RemindRequestReviewerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  reviewer_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "reviewer_id": "reviewerId",
  });
});
/** @internal */
export type RemindRequestReviewerRequest$Outbound = {
  id: string;
  reviewer_id: string;
};

/** @internal */
export const RemindRequestReviewerRequest$outboundSchema: z.ZodType<
  RemindRequestReviewerRequest$Outbound,
  z.ZodTypeDef,
  RemindRequestReviewerRequest
> = z.object({
  id: z.string(),
  reviewerId: z.string(),
}).transform((v) => {
  return remap$(v, {
    reviewerId: "reviewer_id",
  });
});

export function remindRequestReviewerRequestToJSON(
  remindRequestReviewerRequest: RemindRequestReviewerRequest,
): string {
  return JSON.stringify(
    RemindRequestReviewerRequest$outboundSchema.parse(
      remindRequestReviewerRequest,
    ),
  );
}
export function remindRequestReviewerRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemindRequestReviewerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemindRequestReviewerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemindRequestReviewerRequest' from JSON`,
  );
}

/** @internal */
export const RemindRequestReviewerResponse$inboundSchema: z.ZodType<
  RemindRequestReviewerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});
/** @internal */
export type RemindRequestReviewerResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const RemindRequestReviewerResponse$outboundSchema: z.ZodType<
  RemindRequestReviewerResponse$Outbound,
  z.ZodTypeDef,
  RemindRequestReviewerResponse
> = z.object({
  success: z.boolean(),
});

export function remindRequestReviewerResponseToJSON(
  remindRequestReviewerResponse: RemindRequestReviewerResponse,
): string {
  return JSON.stringify(
    RemindRequestReviewerResponse$outboundSchema.parse(
      remindRequestReviewerResponse,
    ),
  );
}
export function remindRequestReviewerResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemindRequestReviewerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemindRequestReviewerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemindRequestReviewerResponse' from JSON`,
  );
}
