/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveGroupTagRequest = {
  /**
   * The ID of the tag to remove.
   */
  tagId: string;
  /**
   * The ID of the group to remove the tag from.
   */
  groupId: string;
};

/** @internal */
export const RemoveGroupTagRequest$inboundSchema: z.ZodType<
  RemoveGroupTagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tag_id: z.string(),
  group_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tag_id": "tagId",
    "group_id": "groupId",
  });
});

/** @internal */
export type RemoveGroupTagRequest$Outbound = {
  tag_id: string;
  group_id: string;
};

/** @internal */
export const RemoveGroupTagRequest$outboundSchema: z.ZodType<
  RemoveGroupTagRequest$Outbound,
  z.ZodTypeDef,
  RemoveGroupTagRequest
> = z.object({
  tagId: z.string(),
  groupId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tagId: "tag_id",
    groupId: "group_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveGroupTagRequest$ {
  /** @deprecated use `RemoveGroupTagRequest$inboundSchema` instead. */
  export const inboundSchema = RemoveGroupTagRequest$inboundSchema;
  /** @deprecated use `RemoveGroupTagRequest$outboundSchema` instead. */
  export const outboundSchema = RemoveGroupTagRequest$outboundSchema;
  /** @deprecated use `RemoveGroupTagRequest$Outbound` instead. */
  export type Outbound = RemoveGroupTagRequest$Outbound;
}

export function removeGroupTagRequestToJSON(
  removeGroupTagRequest: RemoveGroupTagRequest,
): string {
  return JSON.stringify(
    RemoveGroupTagRequest$outboundSchema.parse(removeGroupTagRequest),
  );
}

export function removeGroupTagRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveGroupTagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveGroupTagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveGroupTagRequest' from JSON`,
  );
}
