/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SetGroupReviewerStagesRequest = {
  /**
   * The ID of the group.
   */
  groupId: string;
  reviewerStageList: components.ReviewerStageList;
};

/** @internal */
export const SetGroupReviewerStagesRequest$inboundSchema: z.ZodType<
  SetGroupReviewerStagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  group_id: z.string(),
  ReviewerStageList: components.ReviewerStageList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "group_id": "groupId",
    "ReviewerStageList": "reviewerStageList",
  });
});

/** @internal */
export type SetGroupReviewerStagesRequest$Outbound = {
  group_id: string;
  ReviewerStageList: components.ReviewerStageList$Outbound;
};

/** @internal */
export const SetGroupReviewerStagesRequest$outboundSchema: z.ZodType<
  SetGroupReviewerStagesRequest$Outbound,
  z.ZodTypeDef,
  SetGroupReviewerStagesRequest
> = z.object({
  groupId: z.string(),
  reviewerStageList: components.ReviewerStageList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    groupId: "group_id",
    reviewerStageList: "ReviewerStageList",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetGroupReviewerStagesRequest$ {
  /** @deprecated use `SetGroupReviewerStagesRequest$inboundSchema` instead. */
  export const inboundSchema = SetGroupReviewerStagesRequest$inboundSchema;
  /** @deprecated use `SetGroupReviewerStagesRequest$outboundSchema` instead. */
  export const outboundSchema = SetGroupReviewerStagesRequest$outboundSchema;
  /** @deprecated use `SetGroupReviewerStagesRequest$Outbound` instead. */
  export type Outbound = SetGroupReviewerStagesRequest$Outbound;
}

export function setGroupReviewerStagesRequestToJSON(
  setGroupReviewerStagesRequest: SetGroupReviewerStagesRequest,
): string {
  return JSON.stringify(
    SetGroupReviewerStagesRequest$outboundSchema.parse(
      setGroupReviewerStagesRequest,
    ),
  );
}

export function setGroupReviewerStagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetGroupReviewerStagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetGroupReviewerStagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetGroupReviewerStagesRequest' from JSON`,
  );
}
