/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SetResourceMessageChannelsRequest = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
  messageChannelIDList: components.MessageChannelIDList;
};

/** @internal */
export const SetResourceMessageChannelsRequest$inboundSchema: z.ZodType<
  SetResourceMessageChannelsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
  MessageChannelIDList: components.MessageChannelIDList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
    "MessageChannelIDList": "messageChannelIDList",
  });
});

/** @internal */
export type SetResourceMessageChannelsRequest$Outbound = {
  resource_id: string;
  MessageChannelIDList: components.MessageChannelIDList$Outbound;
};

/** @internal */
export const SetResourceMessageChannelsRequest$outboundSchema: z.ZodType<
  SetResourceMessageChannelsRequest$Outbound,
  z.ZodTypeDef,
  SetResourceMessageChannelsRequest
> = z.object({
  resourceId: z.string(),
  messageChannelIDList: components.MessageChannelIDList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
    messageChannelIDList: "MessageChannelIDList",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetResourceMessageChannelsRequest$ {
  /** @deprecated use `SetResourceMessageChannelsRequest$inboundSchema` instead. */
  export const inboundSchema = SetResourceMessageChannelsRequest$inboundSchema;
  /** @deprecated use `SetResourceMessageChannelsRequest$outboundSchema` instead. */
  export const outboundSchema =
    SetResourceMessageChannelsRequest$outboundSchema;
  /** @deprecated use `SetResourceMessageChannelsRequest$Outbound` instead. */
  export type Outbound = SetResourceMessageChannelsRequest$Outbound;
}

export function setResourceMessageChannelsRequestToJSON(
  setResourceMessageChannelsRequest: SetResourceMessageChannelsRequest,
): string {
  return JSON.stringify(
    SetResourceMessageChannelsRequest$outboundSchema.parse(
      setResourceMessageChannelsRequest,
    ),
  );
}

export function setResourceMessageChannelsRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetResourceMessageChannelsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetResourceMessageChannelsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetResourceMessageChannelsRequest' from JSON`,
  );
}
