/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SetResourceReviewerStagesRequest = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
  reviewerStageList: components.ReviewerStageList;
};

/** @internal */
export const SetResourceReviewerStagesRequest$inboundSchema: z.ZodType<
  SetResourceReviewerStagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
  ReviewerStageList: components.ReviewerStageList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
    "ReviewerStageList": "reviewerStageList",
  });
});

/** @internal */
export type SetResourceReviewerStagesRequest$Outbound = {
  resource_id: string;
  ReviewerStageList: components.ReviewerStageList$Outbound;
};

/** @internal */
export const SetResourceReviewerStagesRequest$outboundSchema: z.ZodType<
  SetResourceReviewerStagesRequest$Outbound,
  z.ZodTypeDef,
  SetResourceReviewerStagesRequest
> = z.object({
  resourceId: z.string(),
  reviewerStageList: components.ReviewerStageList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
    reviewerStageList: "ReviewerStageList",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetResourceReviewerStagesRequest$ {
  /** @deprecated use `SetResourceReviewerStagesRequest$inboundSchema` instead. */
  export const inboundSchema = SetResourceReviewerStagesRequest$inboundSchema;
  /** @deprecated use `SetResourceReviewerStagesRequest$outboundSchema` instead. */
  export const outboundSchema = SetResourceReviewerStagesRequest$outboundSchema;
  /** @deprecated use `SetResourceReviewerStagesRequest$Outbound` instead. */
  export type Outbound = SetResourceReviewerStagesRequest$Outbound;
}

export function setResourceReviewerStagesRequestToJSON(
  setResourceReviewerStagesRequest: SetResourceReviewerStagesRequest,
): string {
  return JSON.stringify(
    SetResourceReviewerStagesRequest$outboundSchema.parse(
      setResourceReviewerStagesRequest,
    ),
  );
}

export function setResourceReviewerStagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetResourceReviewerStagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetResourceReviewerStagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetResourceReviewerStagesRequest' from JSON`,
  );
}
