/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateCampaignRequest = {
  /**
   * The ID of the campaign.
   */
  campaignId: string;
  updateCampaignInfo: components.UpdateCampaignInfo;
};

/** @internal */
export const UpdateCampaignRequest$inboundSchema: z.ZodType<
  UpdateCampaignRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  campaign_id: z.string(),
  UpdateCampaignInfo: components.UpdateCampaignInfo$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "campaign_id": "campaignId",
    "UpdateCampaignInfo": "updateCampaignInfo",
  });
});
/** @internal */
export type UpdateCampaignRequest$Outbound = {
  campaign_id: string;
  UpdateCampaignInfo: components.UpdateCampaignInfo$Outbound;
};

/** @internal */
export const UpdateCampaignRequest$outboundSchema: z.ZodType<
  UpdateCampaignRequest$Outbound,
  z.ZodTypeDef,
  UpdateCampaignRequest
> = z.object({
  campaignId: z.string(),
  updateCampaignInfo: components.UpdateCampaignInfo$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    campaignId: "campaign_id",
    updateCampaignInfo: "UpdateCampaignInfo",
  });
});

export function updateCampaignRequestToJSON(
  updateCampaignRequest: UpdateCampaignRequest,
): string {
  return JSON.stringify(
    UpdateCampaignRequest$outboundSchema.parse(updateCampaignRequest),
  );
}
export function updateCampaignRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCampaignRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCampaignRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCampaignRequest' from JSON`,
  );
}
