/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Derived aggregate status for a campaign item. Matches the admin Reviews
 *
 * @remarks
 * tab Status column labels (undecided items on a stopped campaign are
 * PENDING, not a separate stopped status).
 */
export const CampaignItemStatusEnum = {
  Pending: "PENDING",
  Completed: "COMPLETED",
  Approved: "APPROVED",
  Revoked: "REVOKED",
  NoAction: "NO_ACTION",
  ChangedRole: "CHANGED_ROLE",
  AdminRevoked: "ADMIN_REVOKED",
} as const;
/**
 * Derived aggregate status for a campaign item. Matches the admin Reviews
 *
 * @remarks
 * tab Status column labels (undecided items on a stopped campaign are
 * PENDING, not a separate stopped status).
 */
export type CampaignItemStatusEnum = ClosedEnum<typeof CampaignItemStatusEnum>;

/** @internal */
export const CampaignItemStatusEnum$inboundSchema: z.ZodNativeEnum<
  typeof CampaignItemStatusEnum
> = z.nativeEnum(CampaignItemStatusEnum);
/** @internal */
export const CampaignItemStatusEnum$outboundSchema: z.ZodNativeEnum<
  typeof CampaignItemStatusEnum
> = CampaignItemStatusEnum$inboundSchema;
