/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessEntityFilters,
  AccessEntityFilters$inboundSchema,
  AccessEntityFilters$Outbound,
  AccessEntityFilters$outboundSchema,
} from "./accessentityfilters.js";
import {
  AccessRelationshipFilters,
  AccessRelationshipFilters$inboundSchema,
  AccessRelationshipFilters$Outbound,
  AccessRelationshipFilters$outboundSchema,
} from "./accessrelationshipfilters.js";
import {
  CampaignGroupAssetVisibilityPolicyEnum,
  CampaignGroupAssetVisibilityPolicyEnum$inboundSchema,
  CampaignGroupAssetVisibilityPolicyEnum$outboundSchema,
} from "./campaigngroupassetvisibilitypolicyenum.js";
import {
  CampaignRevokeOnEnum,
  CampaignRevokeOnEnum$inboundSchema,
  CampaignRevokeOnEnum$outboundSchema,
} from "./campaignrevokeonenum.js";
import {
  CampaignStatusEnum,
  CampaignStatusEnum$inboundSchema,
  CampaignStatusEnum$outboundSchema,
} from "./campaignstatusenum.js";
import {
  OpalAccessPathEdgeFilter,
  OpalAccessPathEdgeFilter$inboundSchema,
  OpalAccessPathEdgeFilter$Outbound,
  OpalAccessPathEdgeFilter$outboundSchema,
} from "./opalaccesspathedgefilter.js";
import {
  UARReviewerAssignmentPolicyEnum,
  UARReviewerAssignmentPolicyEnum$inboundSchema,
  UARReviewerAssignmentPolicyEnum$outboundSchema,
} from "./uarreviewerassignmentpolicyenum.js";

/**
 * Access-path query defining the scope of access to review. Uses the same principalFilter / entitlementFilter shape as ACCESS_PATH OpalQuery.
 */
export type Query = {
  /**
   * Filters for matching entities by type, name, tag, IDs, connections, or access levels. Supports recursive logical composition via allOf/anyOf.
   */
  principalFilter?: AccessEntityFilters | undefined;
  /**
   * Filters for matching entities by type, name, tag, IDs, connections, or access levels. Supports recursive logical composition via allOf/anyOf.
   */
  entitlementFilter?: AccessEntityFilters | undefined;
  /**
   * Filters the returned nodes by the access edges connected to them. When `isAccessibleBy` and `hasAccessTo` are provided, the returned nodes must satisfy both edge constraints simultaneously.
   *
   * @remarks
   */
  principalAccessFilters?: AccessRelationshipFilters | undefined;
  /**
   * Filters the returned nodes by the access edges connected to them. When `isAccessibleBy` and `hasAccessTo` are provided, the returned nodes must satisfy both edge constraints simultaneously.
   *
   * @remarks
   */
  entitlementAccessFilters?: AccessRelationshipFilters | undefined;
  /**
   * Filter by access-level remote IDs on the terminal edge.
   */
  accessLevelRemoteIds?: Array<string> | undefined;
  /**
   * Filter by access-level display names on the terminal edge.
   */
  accessLevelNames?: Array<string> | undefined;
  /**
   * Constraints on the access path edges themselves.
   */
  edgeFilter?: OpalAccessPathEdgeFilter | undefined;
};

/**
 * The campaign's configuration, if set.
 */
export type Configuration = {
  /**
   * The ID of the campaign configuration.
   */
  configurationId: string;
  /**
   * The creation time of the configuration.
   */
  createdAt: Date;
  /**
   * The last updated time of the configuration.
   */
  updatedAt: Date;
  /**
   * Access-path query defining the scope of access to review. Uses the same principalFilter / entitlementFilter shape as ACCESS_PATH OpalQuery.
   */
  query?: Query | null | undefined;
  /**
   * A policy for auto-assigning reviewers. If auto-assignment is on, specific assignments can still be manually adjusted after the access review is started. Default is Manually. BY_OWNING_TEAM_ADMIN assigns reviews to resource admins in round-robin fashion. BY_OWNING_TEAM_ADMIN_ALL assigns reviews to all resource admins. BY_APPROVERS assigns reviews to resource approvers in round-robin fashion. BY_APPROVERS_ALL assigns reviews to all resource approvers.
   */
  reviewerAssignmentPolicy: UARReviewerAssignmentPolicyEnum;
  /**
   * Whether reviewers can review their own access.
   */
  allowSelfReview: boolean;
  /**
   * Whether to notify reviewers upon assignment.
   */
  sendReviewerAssignmentNotification: boolean;
  /**
   * Whether reviewers may reassign their reviews to another user.
   */
  allowReviewerReassignment: boolean;
  /**
   * Scheduled start date of the campaign.
   */
  startDate?: Date | null | undefined;
  /**
   * Scheduled end date of the campaign.
   */
  endDate?: Date | null | undefined;
  /**
   * IANA timezone used to interpret campaign deadlines (e.g. America/Los_Angeles).
   */
  timezone: string;
  /**
   * When access decisions take effect during a campaign.
   */
  revokeOn: CampaignRevokeOnEnum;
  /**
   * Days before end date to send reminder notifications.
   */
  reminderSchedule?: Array<number> | undefined;
  /**
   * Whether to include the reviewer's manager in reminders.
   */
  reminderIncludeManager: boolean;
  /**
   * Whether reviewers must provide a reason when denying (revoking) access.
   */
  requireReasonOnDenial: boolean;
  /**
   * Whether AI suggestions are hidden from reviewers.
   */
  hideAiSuggestions: boolean;
  /**
   * Optional custom message included when notifying reviewers that the campaign started.
   */
  customStartMessage?: string | null | undefined;
  /**
   * Controls what group assets reviewers can see during the campaign.
   */
  groupAssetVisibilityPolicy: CampaignGroupAssetVisibilityPolicyEnum;
  /**
   * Whether this configuration is a recurring schedule template.
   */
  isTemplate: boolean;
  /**
   * Cron expression driving the recurring schedule. Null for one-off campaigns.
   */
  cronExpression?: string | null | undefined;
  /**
   * Next time a draft will be generated from this template.
   */
  nextScheduledRun?: Date | null | undefined;
  /**
   * Most recent time a draft was generated from this template.
   */
  lastScheduledRun?: Date | null | undefined;
  /**
   * Deadline window in days applied to each draft generated from this template.
   */
  recurringDurationDays?: number | null | undefined;
};

/**
 * An access review campaign.
 */
export type Campaign = {
  /**
   * The ID of the campaign.
   */
  campaignId: string;
  /**
   * The name of the campaign.
   */
  name: string;
  /**
   * The current status of a campaign.
   */
  status: CampaignStatusEnum;
  /**
   * Whether this campaign is a recurring schedule template. Templates spawn draft campaigns on schedule rather than being reviewed directly.
   */
  isTemplate: boolean;
  /**
   * The creation time of the campaign.
   */
  createdAt: Date;
  /**
   * The last updated time of the campaign.
   */
  updatedAt: Date;
  /**
   * The ID of the user who created the campaign.
   */
  createdByUserId: string;
  /**
   * The campaign's configuration, if set.
   */
  configuration?: Configuration | null | undefined;
  /**
   * The time the campaign was started, if started.
   */
  startedAt?: Date | null | undefined;
  /**
   * The ID of the user who started the campaign, if started.
   */
  startedByUserId?: string | null | undefined;
  /**
   * The time the campaign was manually stopped, if stopped.
   */
  stoppedAt?: Date | null | undefined;
  /**
   * The ID of the user who stopped the campaign, if stopped.
   */
  stoppedByUserId?: string | null | undefined;
  /**
   * The time the campaign reached its scheduled end, if ended.
   */
  endedAt?: Date | null | undefined;
  /**
   * The ID of the user who ended the campaign, if ended.
   */
  endedByUserId?: string | null | undefined;
};

/** @internal */
export const Query$inboundSchema: z.ZodType<Query, z.ZodTypeDef, unknown> = z
  .object({
    principalFilter: AccessEntityFilters$inboundSchema.optional(),
    entitlementFilter: AccessEntityFilters$inboundSchema.optional(),
    principalAccessFilters: AccessRelationshipFilters$inboundSchema.optional(),
    entitlementAccessFilters: AccessRelationshipFilters$inboundSchema
      .optional(),
    accessLevelRemoteIds: z.array(z.string()).optional(),
    accessLevelNames: z.array(z.string()).optional(),
    edgeFilter: OpalAccessPathEdgeFilter$inboundSchema.optional(),
  });
/** @internal */
export type Query$Outbound = {
  principalFilter?: AccessEntityFilters$Outbound | undefined;
  entitlementFilter?: AccessEntityFilters$Outbound | undefined;
  principalAccessFilters?: AccessRelationshipFilters$Outbound | undefined;
  entitlementAccessFilters?: AccessRelationshipFilters$Outbound | undefined;
  accessLevelRemoteIds?: Array<string> | undefined;
  accessLevelNames?: Array<string> | undefined;
  edgeFilter?: OpalAccessPathEdgeFilter$Outbound | undefined;
};

/** @internal */
export const Query$outboundSchema: z.ZodType<
  Query$Outbound,
  z.ZodTypeDef,
  Query
> = z.object({
  principalFilter: AccessEntityFilters$outboundSchema.optional(),
  entitlementFilter: AccessEntityFilters$outboundSchema.optional(),
  principalAccessFilters: AccessRelationshipFilters$outboundSchema.optional(),
  entitlementAccessFilters: AccessRelationshipFilters$outboundSchema.optional(),
  accessLevelRemoteIds: z.array(z.string()).optional(),
  accessLevelNames: z.array(z.string()).optional(),
  edgeFilter: OpalAccessPathEdgeFilter$outboundSchema.optional(),
});

export function queryToJSON(query: Query): string {
  return JSON.stringify(Query$outboundSchema.parse(query));
}
export function queryFromJSON(
  jsonString: string,
): SafeParseResult<Query, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Query$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Query' from JSON`,
  );
}

/** @internal */
export const Configuration$inboundSchema: z.ZodType<
  Configuration,
  z.ZodTypeDef,
  unknown
> = z.object({
  configuration_id: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  query: z.nullable(z.lazy(() => Query$inboundSchema)).optional(),
  reviewer_assignment_policy: UARReviewerAssignmentPolicyEnum$inboundSchema,
  allow_self_review: z.boolean(),
  send_reviewer_assignment_notification: z.boolean(),
  allow_reviewer_reassignment: z.boolean(),
  start_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  end_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  timezone: z.string(),
  revoke_on: CampaignRevokeOnEnum$inboundSchema,
  reminder_schedule: z.array(z.number().int()).optional(),
  reminder_include_manager: z.boolean(),
  require_reason_on_denial: z.boolean(),
  hide_ai_suggestions: z.boolean(),
  custom_start_message: z.nullable(z.string()).optional(),
  group_asset_visibility_policy:
    CampaignGroupAssetVisibilityPolicyEnum$inboundSchema,
  is_template: z.boolean(),
  cron_expression: z.nullable(z.string()).optional(),
  next_scheduled_run: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  last_scheduled_run: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  recurring_duration_days: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "configuration_id": "configurationId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "reviewer_assignment_policy": "reviewerAssignmentPolicy",
    "allow_self_review": "allowSelfReview",
    "send_reviewer_assignment_notification":
      "sendReviewerAssignmentNotification",
    "allow_reviewer_reassignment": "allowReviewerReassignment",
    "start_date": "startDate",
    "end_date": "endDate",
    "revoke_on": "revokeOn",
    "reminder_schedule": "reminderSchedule",
    "reminder_include_manager": "reminderIncludeManager",
    "require_reason_on_denial": "requireReasonOnDenial",
    "hide_ai_suggestions": "hideAiSuggestions",
    "custom_start_message": "customStartMessage",
    "group_asset_visibility_policy": "groupAssetVisibilityPolicy",
    "is_template": "isTemplate",
    "cron_expression": "cronExpression",
    "next_scheduled_run": "nextScheduledRun",
    "last_scheduled_run": "lastScheduledRun",
    "recurring_duration_days": "recurringDurationDays",
  });
});
/** @internal */
export type Configuration$Outbound = {
  configuration_id: string;
  created_at: string;
  updated_at: string;
  query?: Query$Outbound | null | undefined;
  reviewer_assignment_policy: string;
  allow_self_review: boolean;
  send_reviewer_assignment_notification: boolean;
  allow_reviewer_reassignment: boolean;
  start_date?: string | null | undefined;
  end_date?: string | null | undefined;
  timezone: string;
  revoke_on: string;
  reminder_schedule?: Array<number> | undefined;
  reminder_include_manager: boolean;
  require_reason_on_denial: boolean;
  hide_ai_suggestions: boolean;
  custom_start_message?: string | null | undefined;
  group_asset_visibility_policy: string;
  is_template: boolean;
  cron_expression?: string | null | undefined;
  next_scheduled_run?: string | null | undefined;
  last_scheduled_run?: string | null | undefined;
  recurring_duration_days?: number | null | undefined;
};

/** @internal */
export const Configuration$outboundSchema: z.ZodType<
  Configuration$Outbound,
  z.ZodTypeDef,
  Configuration
> = z.object({
  configurationId: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
  query: z.nullable(z.lazy(() => Query$outboundSchema)).optional(),
  reviewerAssignmentPolicy: UARReviewerAssignmentPolicyEnum$outboundSchema,
  allowSelfReview: z.boolean(),
  sendReviewerAssignmentNotification: z.boolean(),
  allowReviewerReassignment: z.boolean(),
  startDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  endDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  timezone: z.string(),
  revokeOn: CampaignRevokeOnEnum$outboundSchema,
  reminderSchedule: z.array(z.number().int()).optional(),
  reminderIncludeManager: z.boolean(),
  requireReasonOnDenial: z.boolean(),
  hideAiSuggestions: z.boolean(),
  customStartMessage: z.nullable(z.string()).optional(),
  groupAssetVisibilityPolicy:
    CampaignGroupAssetVisibilityPolicyEnum$outboundSchema,
  isTemplate: z.boolean(),
  cronExpression: z.nullable(z.string()).optional(),
  nextScheduledRun: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastScheduledRun: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  recurringDurationDays: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    configurationId: "configuration_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
    reviewerAssignmentPolicy: "reviewer_assignment_policy",
    allowSelfReview: "allow_self_review",
    sendReviewerAssignmentNotification: "send_reviewer_assignment_notification",
    allowReviewerReassignment: "allow_reviewer_reassignment",
    startDate: "start_date",
    endDate: "end_date",
    revokeOn: "revoke_on",
    reminderSchedule: "reminder_schedule",
    reminderIncludeManager: "reminder_include_manager",
    requireReasonOnDenial: "require_reason_on_denial",
    hideAiSuggestions: "hide_ai_suggestions",
    customStartMessage: "custom_start_message",
    groupAssetVisibilityPolicy: "group_asset_visibility_policy",
    isTemplate: "is_template",
    cronExpression: "cron_expression",
    nextScheduledRun: "next_scheduled_run",
    lastScheduledRun: "last_scheduled_run",
    recurringDurationDays: "recurring_duration_days",
  });
});

export function configurationToJSON(configuration: Configuration): string {
  return JSON.stringify(Configuration$outboundSchema.parse(configuration));
}
export function configurationFromJSON(
  jsonString: string,
): SafeParseResult<Configuration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Configuration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Configuration' from JSON`,
  );
}

/** @internal */
export const Campaign$inboundSchema: z.ZodType<
  Campaign,
  z.ZodTypeDef,
  unknown
> = z.object({
  campaign_id: z.string(),
  name: z.string(),
  status: CampaignStatusEnum$inboundSchema,
  is_template: z.boolean(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  created_by_user_id: z.string(),
  configuration: z.nullable(z.lazy(() => Configuration$inboundSchema))
    .optional(),
  started_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  started_by_user_id: z.nullable(z.string()).optional(),
  stopped_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  stopped_by_user_id: z.nullable(z.string()).optional(),
  ended_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  ended_by_user_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "campaign_id": "campaignId",
    "is_template": "isTemplate",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "created_by_user_id": "createdByUserId",
    "started_at": "startedAt",
    "started_by_user_id": "startedByUserId",
    "stopped_at": "stoppedAt",
    "stopped_by_user_id": "stoppedByUserId",
    "ended_at": "endedAt",
    "ended_by_user_id": "endedByUserId",
  });
});
/** @internal */
export type Campaign$Outbound = {
  campaign_id: string;
  name: string;
  status: string;
  is_template: boolean;
  created_at: string;
  updated_at: string;
  created_by_user_id: string;
  configuration?: Configuration$Outbound | null | undefined;
  started_at?: string | null | undefined;
  started_by_user_id?: string | null | undefined;
  stopped_at?: string | null | undefined;
  stopped_by_user_id?: string | null | undefined;
  ended_at?: string | null | undefined;
  ended_by_user_id?: string | null | undefined;
};

/** @internal */
export const Campaign$outboundSchema: z.ZodType<
  Campaign$Outbound,
  z.ZodTypeDef,
  Campaign
> = z.object({
  campaignId: z.string(),
  name: z.string(),
  status: CampaignStatusEnum$outboundSchema,
  isTemplate: z.boolean(),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
  createdByUserId: z.string(),
  configuration: z.nullable(z.lazy(() => Configuration$outboundSchema))
    .optional(),
  startedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  startedByUserId: z.nullable(z.string()).optional(),
  stoppedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  stoppedByUserId: z.nullable(z.string()).optional(),
  endedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  endedByUserId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    campaignId: "campaign_id",
    isTemplate: "is_template",
    createdAt: "created_at",
    updatedAt: "updated_at",
    createdByUserId: "created_by_user_id",
    startedAt: "started_at",
    startedByUserId: "started_by_user_id",
    stoppedAt: "stopped_at",
    stoppedByUserId: "stopped_by_user_id",
    endedAt: "ended_at",
    endedByUserId: "ended_by_user_id",
  });
});

export function campaignToJSON(campaign: Campaign): string {
  return JSON.stringify(Campaign$outboundSchema.parse(campaign));
}
export function campaignFromJSON(
  jsonString: string,
): SafeParseResult<Campaign, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Campaign$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Campaign' from JSON`,
  );
}
