/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CampaignItemReviewerAssignmentSourceEnum,
  CampaignItemReviewerAssignmentSourceEnum$inboundSchema,
  CampaignItemReviewerAssignmentSourceEnum$outboundSchema,
} from "./campaignitemreviewerassignmentsourceenum.js";

/**
 * Pair of campaign item and reviewer to assign or unassign.
 */
export type CampaignItemReviewerAssignment = {
  /**
   * The ID of the campaign item.
   */
  campaignItemId: string;
  /**
   * The ID of the reviewer. Required when `assignment_source` is `MANUAL`
   *
   * @remarks
   * (or omitted), and required for every unassign entry.
   */
  reviewerId?: string | null | undefined;
  /**
   * Defaults to `MANUAL`. When `PRINCIPAL_MANAGER` or `ASSET_ADMIN_OWNER`,
   *
   * @remarks
   * the backend resolves reviewer ID(s) and `reviewer_id` may be omitted.
   */
  assignmentSource?: CampaignItemReviewerAssignmentSourceEnum | undefined;
};

/** @internal */
export const CampaignItemReviewerAssignment$inboundSchema: z.ZodType<
  CampaignItemReviewerAssignment,
  z.ZodTypeDef,
  unknown
> = z.object({
  campaign_item_id: z.string(),
  reviewer_id: z.nullable(z.string()).optional(),
  assignment_source: CampaignItemReviewerAssignmentSourceEnum$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "campaign_item_id": "campaignItemId",
    "reviewer_id": "reviewerId",
    "assignment_source": "assignmentSource",
  });
});
/** @internal */
export type CampaignItemReviewerAssignment$Outbound = {
  campaign_item_id: string;
  reviewer_id?: string | null | undefined;
  assignment_source?: string | undefined;
};

/** @internal */
export const CampaignItemReviewerAssignment$outboundSchema: z.ZodType<
  CampaignItemReviewerAssignment$Outbound,
  z.ZodTypeDef,
  CampaignItemReviewerAssignment
> = z.object({
  campaignItemId: z.string(),
  reviewerId: z.nullable(z.string()).optional(),
  assignmentSource: CampaignItemReviewerAssignmentSourceEnum$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    campaignItemId: "campaign_item_id",
    reviewerId: "reviewer_id",
    assignmentSource: "assignment_source",
  });
});

export function campaignItemReviewerAssignmentToJSON(
  campaignItemReviewerAssignment: CampaignItemReviewerAssignment,
): string {
  return JSON.stringify(
    CampaignItemReviewerAssignment$outboundSchema.parse(
      campaignItemReviewerAssignment,
    ),
  );
}
export function campaignItemReviewerAssignmentFromJSON(
  jsonString: string,
): SafeParseResult<CampaignItemReviewerAssignment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignItemReviewerAssignment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignItemReviewerAssignment' from JSON`,
  );
}
