/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppTypeEnum,
  AppTypeEnum$inboundSchema,
  AppTypeEnum$outboundSchema,
} from "./apptypeenum.js";
import {
  CreateCustomConnectorInfo,
  CreateCustomConnectorInfo$inboundSchema,
  CreateCustomConnectorInfo$Outbound,
  CreateCustomConnectorInfo$outboundSchema,
} from "./createcustomconnectorinfo.js";
import {
  VisibilityTypeEnum,
  VisibilityTypeEnum$inboundSchema,
  VisibilityTypeEnum$outboundSchema,
} from "./visibilitytypeenum.js";

/**
 * Information needed to create an app. Currently supports only Push-only
 *
 * @remarks
 * apps (`CUSTOM`) and Custom Connector apps (`CUSTOM_CONNECTOR`).
 */
export type CreateAppInfo = {
  /**
   * The name of the app.
   */
  name: string;
  /**
   * A description of the app.
   */
  description: string;
  /**
   * The ID of the owner of the app.
   */
  adminOwnerId: string;
  /**
   * The type of an app.
   */
  appType: AppTypeEnum;
  /**
   * The visibility level of the entity.
   */
  visibility?: VisibilityTypeEnum | undefined;
  /**
   * The IDs of groups that can see this app when visibility is `LIMITED`.
   */
  visibilityGroupIds?: Array<string> | undefined;
  /**
   * The visibility level of the entity.
   */
  importVisibility?: VisibilityTypeEnum | undefined;
  /**
   * Information needed to create a Custom Connector app.
   */
  customConnector?: CreateCustomConnectorInfo | undefined;
};

/** @internal */
export const CreateAppInfo$inboundSchema: z.ZodType<
  CreateAppInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string(),
  admin_owner_id: z.string(),
  app_type: AppTypeEnum$inboundSchema,
  visibility: VisibilityTypeEnum$inboundSchema.optional(),
  visibility_group_ids: z.array(z.string()).optional(),
  import_visibility: VisibilityTypeEnum$inboundSchema.optional(),
  custom_connector: CreateCustomConnectorInfo$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "admin_owner_id": "adminOwnerId",
    "app_type": "appType",
    "visibility_group_ids": "visibilityGroupIds",
    "import_visibility": "importVisibility",
    "custom_connector": "customConnector",
  });
});
/** @internal */
export type CreateAppInfo$Outbound = {
  name: string;
  description: string;
  admin_owner_id: string;
  app_type: string;
  visibility?: string | undefined;
  visibility_group_ids?: Array<string> | undefined;
  import_visibility?: string | undefined;
  custom_connector?: CreateCustomConnectorInfo$Outbound | undefined;
};

/** @internal */
export const CreateAppInfo$outboundSchema: z.ZodType<
  CreateAppInfo$Outbound,
  z.ZodTypeDef,
  CreateAppInfo
> = z.object({
  name: z.string(),
  description: z.string(),
  adminOwnerId: z.string(),
  appType: AppTypeEnum$outboundSchema,
  visibility: VisibilityTypeEnum$outboundSchema.optional(),
  visibilityGroupIds: z.array(z.string()).optional(),
  importVisibility: VisibilityTypeEnum$outboundSchema.optional(),
  customConnector: CreateCustomConnectorInfo$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    adminOwnerId: "admin_owner_id",
    appType: "app_type",
    visibilityGroupIds: "visibility_group_ids",
    importVisibility: "import_visibility",
    customConnector: "custom_connector",
  });
});

export function createAppInfoToJSON(createAppInfo: CreateAppInfo): string {
  return JSON.stringify(CreateAppInfo$outboundSchema.parse(createAppInfo));
}
export function createAppInfoFromJSON(
  jsonString: string,
): SafeParseResult<CreateAppInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAppInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAppInfo' from JSON`,
  );
}
