/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ResourceAccessLevel,
  ResourceAccessLevel$inboundSchema,
  ResourceAccessLevel$Outbound,
  ResourceAccessLevel$outboundSchema,
} from "./resourceaccesslevel.js";

/**
 * Info for creating a custom access level.
 */
export type CreateResourceCustomAccessLevelInfo = {
  /**
   * # Access Level Object
   *
   * @remarks
   * ### Description
   * The `AccessLevel` object is used to represent the level of access that a principal has. The "default" access
   * level is a `AccessLevel` object whose fields are all empty strings.
   *
   * ### Usage Example
   * View the `AccessLevel` of a resource/user or resource/group pair to see the level of access granted to the resource.
   */
  accessLevel: ResourceAccessLevel;
  /**
   * The policy document.
   */
  policy?: string | null | undefined;
  /**
   * Whether the role is requestable. Defaults to false.
   */
  requestableByDefault?: boolean | undefined;
  /**
   * The sensitivity index. Null to leave unranked.
   */
  stackableSensitivityIndex?: number | null | undefined;
};

/** @internal */
export const CreateResourceCustomAccessLevelInfo$inboundSchema: z.ZodType<
  CreateResourceCustomAccessLevelInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_level: ResourceAccessLevel$inboundSchema,
  policy: z.nullable(z.string()).optional(),
  requestable_by_default: z.boolean().optional(),
  stackable_sensitivity_index: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "access_level": "accessLevel",
    "requestable_by_default": "requestableByDefault",
    "stackable_sensitivity_index": "stackableSensitivityIndex",
  });
});
/** @internal */
export type CreateResourceCustomAccessLevelInfo$Outbound = {
  access_level: ResourceAccessLevel$Outbound;
  policy?: string | null | undefined;
  requestable_by_default?: boolean | undefined;
  stackable_sensitivity_index?: number | null | undefined;
};

/** @internal */
export const CreateResourceCustomAccessLevelInfo$outboundSchema: z.ZodType<
  CreateResourceCustomAccessLevelInfo$Outbound,
  z.ZodTypeDef,
  CreateResourceCustomAccessLevelInfo
> = z.object({
  accessLevel: ResourceAccessLevel$outboundSchema,
  policy: z.nullable(z.string()).optional(),
  requestableByDefault: z.boolean().optional(),
  stackableSensitivityIndex: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    accessLevel: "access_level",
    requestableByDefault: "requestable_by_default",
    stackableSensitivityIndex: "stackable_sensitivity_index",
  });
});

export function createResourceCustomAccessLevelInfoToJSON(
  createResourceCustomAccessLevelInfo: CreateResourceCustomAccessLevelInfo,
): string {
  return JSON.stringify(
    CreateResourceCustomAccessLevelInfo$outboundSchema.parse(
      createResourceCustomAccessLevelInfo,
    ),
  );
}
export function createResourceCustomAccessLevelInfoFromJSON(
  jsonString: string,
): SafeParseResult<CreateResourceCustomAccessLevelInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateResourceCustomAccessLevelInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResourceCustomAccessLevelInfo' from JSON`,
  );
}
