/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request body for creating a new delegation of access review requests from one user to another.
 */
export type CreateDelegationRequest = {
  /**
   * The ID of the user delegating their access review requests.
   */
  delegatorUserId: string;
  /**
   * The ID of the user being delegated to.
   */
  delegateUserId: string;
  /**
   * The start time of the delegation.
   */
  startTime: Date;
  /**
   * The end time of the delegation.
   */
  endTime: Date;
  /**
   * The reason for the delegation.
   */
  reason: string;
};

/** @internal */
export const CreateDelegationRequest$inboundSchema: z.ZodType<
  CreateDelegationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  delegator_user_id: z.string(),
  delegate_user_id: z.string(),
  start_time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  end_time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  reason: z.string(),
}).transform((v) => {
  return remap$(v, {
    "delegator_user_id": "delegatorUserId",
    "delegate_user_id": "delegateUserId",
    "start_time": "startTime",
    "end_time": "endTime",
  });
});

/** @internal */
export type CreateDelegationRequest$Outbound = {
  delegator_user_id: string;
  delegate_user_id: string;
  start_time: string;
  end_time: string;
  reason: string;
};

/** @internal */
export const CreateDelegationRequest$outboundSchema: z.ZodType<
  CreateDelegationRequest$Outbound,
  z.ZodTypeDef,
  CreateDelegationRequest
> = z.object({
  delegatorUserId: z.string(),
  delegateUserId: z.string(),
  startTime: z.date().transform(v => v.toISOString()),
  endTime: z.date().transform(v => v.toISOString()),
  reason: z.string(),
}).transform((v) => {
  return remap$(v, {
    delegatorUserId: "delegator_user_id",
    delegateUserId: "delegate_user_id",
    startTime: "start_time",
    endTime: "end_time",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDelegationRequest$ {
  /** @deprecated use `CreateDelegationRequest$inboundSchema` instead. */
  export const inboundSchema = CreateDelegationRequest$inboundSchema;
  /** @deprecated use `CreateDelegationRequest$outboundSchema` instead. */
  export const outboundSchema = CreateDelegationRequest$outboundSchema;
  /** @deprecated use `CreateDelegationRequest$Outbound` instead. */
  export type Outbound = CreateDelegationRequest$Outbound;
}

export function createDelegationRequestToJSON(
  createDelegationRequest: CreateDelegationRequest,
): string {
  return JSON.stringify(
    CreateDelegationRequest$outboundSchema.parse(createDelegationRequest),
  );
}

export function createDelegationRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateDelegationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDelegationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDelegationRequest' from JSON`,
  );
}
