/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "./token.js";

/**
 * The created API token. `signed_token` is the secret credential and is
 *
 * @remarks
 * only returned once at creation time.
 */
export type CreateTokenResponse = {
  /**
   * A first-party API token.
   */
  token: Token;
  /**
   * The secret token string. Store this securely; it is only returned
   *
   * @remarks
   * once at creation time.
   */
  signedToken: string;
};

/** @internal */
export const CreateTokenResponse$inboundSchema: z.ZodType<
  CreateTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: Token$inboundSchema,
  signed_token: z.string(),
}).transform((v) => {
  return remap$(v, {
    "signed_token": "signedToken",
  });
});
/** @internal */
export type CreateTokenResponse$Outbound = {
  token: Token$Outbound;
  signed_token: string;
};

/** @internal */
export const CreateTokenResponse$outboundSchema: z.ZodType<
  CreateTokenResponse$Outbound,
  z.ZodTypeDef,
  CreateTokenResponse
> = z.object({
  token: Token$outboundSchema,
  signedToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    signedToken: "signed_token",
  });
});

export function createTokenResponseToJSON(
  createTokenResponse: CreateTokenResponse,
): string {
  return JSON.stringify(
    CreateTokenResponse$outboundSchema.parse(createTokenResponse),
  );
}
export function createTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTokenResponse' from JSON`,
  );
}
