/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Configuration for a Custom Connector app. Does not include the signing
 *
 * @remarks
 * secret; secrets are write-only and never returned by the API.
 */
export type CustomConnectorAppConfig = {
  /**
   * The identifier of the Custom Connector.
   */
  identifier: string;
  /**
   * The base URL of the Custom Connector.
   */
  baseUrl: string;
  /**
   * Whether TLS verification is enabled for the Custom Connector.
   */
  tlsMode: boolean;
  /**
   * Optional PEM-encoded CA certificate content for TLS.
   */
  tlsCaCertContent?: string | null | undefined;
  /**
   * Whether the Custom Connector supports groups.
   */
  supportsGroups: boolean;
  /**
   * Whether the Custom Connector supports nested resources.
   */
  supportsNestedResources: boolean;
  /**
   * Whether the Custom Connector supports nested groups.
   */
  supportsNestedGroups: boolean;
  /**
   * Whether the Custom Connector supports event ingestion.
   */
  supportsEventIngestion: boolean;
};

/** @internal */
export const CustomConnectorAppConfig$inboundSchema: z.ZodType<
  CustomConnectorAppConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string(),
  base_url: z.string(),
  tls_mode: z.boolean(),
  tls_ca_cert_content: z.nullable(z.string()).optional(),
  supports_groups: z.boolean(),
  supports_nested_resources: z.boolean(),
  supports_nested_groups: z.boolean(),
  supports_event_ingestion: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "base_url": "baseUrl",
    "tls_mode": "tlsMode",
    "tls_ca_cert_content": "tlsCaCertContent",
    "supports_groups": "supportsGroups",
    "supports_nested_resources": "supportsNestedResources",
    "supports_nested_groups": "supportsNestedGroups",
    "supports_event_ingestion": "supportsEventIngestion",
  });
});
/** @internal */
export type CustomConnectorAppConfig$Outbound = {
  identifier: string;
  base_url: string;
  tls_mode: boolean;
  tls_ca_cert_content?: string | null | undefined;
  supports_groups: boolean;
  supports_nested_resources: boolean;
  supports_nested_groups: boolean;
  supports_event_ingestion: boolean;
};

/** @internal */
export const CustomConnectorAppConfig$outboundSchema: z.ZodType<
  CustomConnectorAppConfig$Outbound,
  z.ZodTypeDef,
  CustomConnectorAppConfig
> = z.object({
  identifier: z.string(),
  baseUrl: z.string(),
  tlsMode: z.boolean(),
  tlsCaCertContent: z.nullable(z.string()).optional(),
  supportsGroups: z.boolean(),
  supportsNestedResources: z.boolean(),
  supportsNestedGroups: z.boolean(),
  supportsEventIngestion: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    baseUrl: "base_url",
    tlsMode: "tls_mode",
    tlsCaCertContent: "tls_ca_cert_content",
    supportsGroups: "supports_groups",
    supportsNestedResources: "supports_nested_resources",
    supportsNestedGroups: "supports_nested_groups",
    supportsEventIngestion: "supports_event_ingestion",
  });
});

export function customConnectorAppConfigToJSON(
  customConnectorAppConfig: CustomConnectorAppConfig,
): string {
  return JSON.stringify(
    CustomConnectorAppConfig$outboundSchema.parse(customConnectorAppConfig),
  );
}
export function customConnectorAppConfigFromJSON(
  jsonString: string,
): SafeParseResult<CustomConnectorAppConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomConnectorAppConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomConnectorAppConfig' from JSON`,
  );
}
