/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of an entity.
 */
export const EntityTypeEnum = {
  Group: "GROUP",
  Resource: "RESOURCE",
  User: "USER",
} as const;
/**
 * The type of an entity.
 */
export type EntityTypeEnum = ClosedEnum<typeof EntityTypeEnum>;

/** @internal */
export const EntityTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof EntityTypeEnum
> = z.nativeEnum(EntityTypeEnum);
/** @internal */
export const EntityTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof EntityTypeEnum
> = EntityTypeEnum$inboundSchema;
