/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filters GROUP and RESOURCE entities by their admin owner. USER entities never match, in either polarity. `not` inverts the match within the resource/group domain (self-negating, like IdpStatusFilter): omit it (or false) to include entities owned by the given owners, set it true to exclude them.
 *
 * @remarks
 */
export type EntityAdminFilter = {
  /**
   * The owner (group) UUIDs to match entities against.
   */
  ownerIDs: Array<string>;
  /**
   * Invert the match — return resources/groups NOT owned by the given owners.
   */
  not?: boolean | undefined;
};

/** @internal */
export const EntityAdminFilter$inboundSchema: z.ZodType<
  EntityAdminFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  ownerIDs: z.array(z.string()),
  not: z.boolean().optional(),
});
/** @internal */
export type EntityAdminFilter$Outbound = {
  ownerIDs: Array<string>;
  not?: boolean | undefined;
};

/** @internal */
export const EntityAdminFilter$outboundSchema: z.ZodType<
  EntityAdminFilter$Outbound,
  z.ZodTypeDef,
  EntityAdminFilter
> = z.object({
  ownerIDs: z.array(z.string()),
  not: z.boolean().optional(),
});

export function entityAdminFilterToJSON(
  entityAdminFilter: EntityAdminFilter,
): string {
  return JSON.stringify(
    EntityAdminFilter$outboundSchema.parse(entityAdminFilter),
  );
}
export function entityAdminFilterFromJSON(
  jsonString: string,
): SafeParseResult<EntityAdminFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntityAdminFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntityAdminFilter' from JSON`,
  );
}
