/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GroupAccessLevel,
  GroupAccessLevel$inboundSchema,
  GroupAccessLevel$Outbound,
  GroupAccessLevel$outboundSchema,
} from "./groupaccesslevel.js";

/**
 * A list of access levels defined for a group.
 */
export type GroupAccessLevelList = {
  results?: Array<GroupAccessLevel> | undefined;
};

/** @internal */
export const GroupAccessLevelList$inboundSchema: z.ZodType<
  GroupAccessLevelList,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(GroupAccessLevel$inboundSchema).optional(),
});
/** @internal */
export type GroupAccessLevelList$Outbound = {
  results?: Array<GroupAccessLevel$Outbound> | undefined;
};

/** @internal */
export const GroupAccessLevelList$outboundSchema: z.ZodType<
  GroupAccessLevelList$Outbound,
  z.ZodTypeDef,
  GroupAccessLevelList
> = z.object({
  results: z.array(GroupAccessLevel$outboundSchema).optional(),
});

export function groupAccessLevelListToJSON(
  groupAccessLevelList: GroupAccessLevelList,
): string {
  return JSON.stringify(
    GroupAccessLevelList$outboundSchema.parse(groupAccessLevelList),
  );
}
export function groupAccessLevelListFromJSON(
  jsonString: string,
): SafeParseResult<GroupAccessLevelList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupAccessLevelList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupAccessLevelList' from JSON`,
  );
}
