/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of the group.
 */
export const GroupTypeEnum = {
  ActiveDirectoryGroup: "ACTIVE_DIRECTORY_GROUP",
  AwsSsoGroup: "AWS_SSO_GROUP",
  DatabricksAccountGroup: "DATABRICKS_ACCOUNT_GROUP",
  DuoGroup: "DUO_GROUP",
  GitHubTeam: "GIT_HUB_TEAM",
  GitLabGroup: "GIT_LAB_GROUP",
  GoogleGroupsGroup: "GOOGLE_GROUPS_GROUP",
  GoogleGroupsGkeGroup: "GOOGLE_GROUPS_GKE_GROUP",
  LdapGroup: "LDAP_GROUP",
  OktaGroup: "OKTA_GROUP",
  OktaGroupRule: "OKTA_GROUP_RULE",
  TailscaleGroup: "TAILSCALE_GROUP",
  OpalGroup: "OPAL_GROUP",
  OpalAccessRule: "OPAL_ACCESS_RULE",
  AzureAdSecurityGroup: "AZURE_AD_SECURITY_GROUP",
  AzureAdMicrosoft365Group: "AZURE_AD_MICROSOFT_365_GROUP",
  ConnectorGroup: "CONNECTOR_GROUP",
  SnowflakeRole: "SNOWFLAKE_ROLE",
  WorkdayUserSecurityGroup: "WORKDAY_USER_SECURITY_GROUP",
} as const;
/**
 * The type of the group.
 */
export type GroupTypeEnum = ClosedEnum<typeof GroupTypeEnum>;

/** @internal */
export const GroupTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof GroupTypeEnum
> = z.nativeEnum(GroupTypeEnum);

/** @internal */
export const GroupTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof GroupTypeEnum
> = GroupTypeEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupTypeEnum$ {
  /** @deprecated use `GroupTypeEnum$inboundSchema` instead. */
  export const inboundSchema = GroupTypeEnum$inboundSchema;
  /** @deprecated use `GroupTypeEnum$outboundSchema` instead. */
  export const outboundSchema = GroupTypeEnum$outboundSchema;
}
