/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * # GroupContainingGroup Object
 *
 * @remarks
 * ### Description
 * The `GroupContainingGroup` object is used to represent a relationship between a group and a group.
 */
export type GroupContainingGroup = {
  /**
   * The groupID of the containing group.
   */
  containingGroupId: string;
  /**
   * The updated duration for which the group can be accessed (in minutes). Use 0 for indefinite.
   */
  durationMinutes?: number | undefined;
  /**
   * The updated remote ID of the access level granted to this group.
   */
  accessLevelRemoteId?: string | undefined;
};

/** @internal */
export const GroupContainingGroup$inboundSchema: z.ZodType<
  GroupContainingGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  containing_group_id: z.string(),
  duration_minutes: z.number().int().optional(),
  access_level_remote_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "containing_group_id": "containingGroupId",
    "duration_minutes": "durationMinutes",
    "access_level_remote_id": "accessLevelRemoteId",
  });
});
/** @internal */
export type GroupContainingGroup$Outbound = {
  containing_group_id: string;
  duration_minutes?: number | undefined;
  access_level_remote_id?: string | undefined;
};

/** @internal */
export const GroupContainingGroup$outboundSchema: z.ZodType<
  GroupContainingGroup$Outbound,
  z.ZodTypeDef,
  GroupContainingGroup
> = z.object({
  containingGroupId: z.string(),
  durationMinutes: z.number().int().optional(),
  accessLevelRemoteId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    containingGroupId: "containing_group_id",
    durationMinutes: "duration_minutes",
    accessLevelRemoteId: "access_level_remote_id",
  });
});

export function groupContainingGroupToJSON(
  groupContainingGroup: GroupContainingGroup,
): string {
  return JSON.stringify(
    GroupContainingGroup$outboundSchema.parse(groupContainingGroup),
  );
}
export function groupContainingGroupFromJSON(
  jsonString: string,
): SafeParseResult<GroupContainingGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupContainingGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupContainingGroup' from JSON`,
  );
}
