/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GroupUser,
  GroupUser$inboundSchema,
  GroupUser$Outbound,
  GroupUser$outboundSchema,
} from "./groupuser.js";

export type GroupUserList = {
  results?: Array<GroupUser> | undefined;
  /**
   * The cursor with which to continue pagination if additional result pages exist.
   */
  next?: string | null | undefined;
  /**
   * The cursor used to obtain the current result page.
   */
  previous?: string | null | undefined;
};

/** @internal */
export const GroupUserList$inboundSchema: z.ZodType<
  GroupUserList,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(GroupUser$inboundSchema).optional(),
  next: z.nullable(z.string()).optional(),
  previous: z.nullable(z.string()).optional(),
});
/** @internal */
export type GroupUserList$Outbound = {
  results?: Array<GroupUser$Outbound> | undefined;
  next?: string | null | undefined;
  previous?: string | null | undefined;
};

/** @internal */
export const GroupUserList$outboundSchema: z.ZodType<
  GroupUserList$Outbound,
  z.ZodTypeDef,
  GroupUserList
> = z.object({
  results: z.array(GroupUser$outboundSchema).optional(),
  next: z.nullable(z.string()).optional(),
  previous: z.nullable(z.string()).optional(),
});

export function groupUserListToJSON(groupUserList: GroupUserList): string {
  return JSON.stringify(GroupUserList$outboundSchema.parse(groupUserList));
}
export function groupUserListFromJSON(
  jsonString: string,
): SafeParseResult<GroupUserList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupUserList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupUserList' from JSON`,
  );
}
