/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IdpGroupMapping,
  IdpGroupMapping$inboundSchema,
  IdpGroupMapping$Outbound,
  IdpGroupMapping$outboundSchema,
} from "./idpgroupmapping.js";

export type IdpGroupMappingList = {
  mappings: Array<IdpGroupMapping>;
};

/** @internal */
export const IdpGroupMappingList$inboundSchema: z.ZodType<
  IdpGroupMappingList,
  z.ZodTypeDef,
  unknown
> = z.object({
  mappings: z.array(IdpGroupMapping$inboundSchema),
});

/** @internal */
export type IdpGroupMappingList$Outbound = {
  mappings: Array<IdpGroupMapping$Outbound>;
};

/** @internal */
export const IdpGroupMappingList$outboundSchema: z.ZodType<
  IdpGroupMappingList$Outbound,
  z.ZodTypeDef,
  IdpGroupMappingList
> = z.object({
  mappings: z.array(IdpGroupMapping$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdpGroupMappingList$ {
  /** @deprecated use `IdpGroupMappingList$inboundSchema` instead. */
  export const inboundSchema = IdpGroupMappingList$inboundSchema;
  /** @deprecated use `IdpGroupMappingList$outboundSchema` instead. */
  export const outboundSchema = IdpGroupMappingList$outboundSchema;
  /** @deprecated use `IdpGroupMappingList$Outbound` instead. */
  export type Outbound = IdpGroupMappingList$Outbound;
}

export function idpGroupMappingListToJSON(
  idpGroupMappingList: IdpGroupMappingList,
): string {
  return JSON.stringify(
    IdpGroupMappingList$outboundSchema.parse(idpGroupMappingList),
  );
}

export function idpGroupMappingListFromJSON(
  jsonString: string,
): SafeParseResult<IdpGroupMappingList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdpGroupMappingList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdpGroupMappingList' from JSON`,
  );
}
