/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UserProductRoleEnum,
  UserProductRoleEnum$inboundSchema,
  UserProductRoleEnum$outboundSchema,
} from "./userproductroleenum.js";

/**
 * The information required to invite a user.
 */
export type InviteUserInfo = {
  email: string;
  firstName: string;
  lastName: string;
  /**
   * The product role assigned to a user.
   */
  role: UserProductRoleEnum;
};

/** @internal */
export const InviteUserInfo$inboundSchema: z.ZodType<
  InviteUserInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  role: UserProductRoleEnum$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
  });
});
/** @internal */
export type InviteUserInfo$Outbound = {
  email: string;
  first_name: string;
  last_name: string;
  role: string;
};

/** @internal */
export const InviteUserInfo$outboundSchema: z.ZodType<
  InviteUserInfo$Outbound,
  z.ZodTypeDef,
  InviteUserInfo
> = z.object({
  email: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  role: UserProductRoleEnum$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    firstName: "first_name",
    lastName: "last_name",
  });
});

export function inviteUserInfoToJSON(inviteUserInfo: InviteUserInfo): string {
  return JSON.stringify(InviteUserInfo$outboundSchema.parse(inviteUserInfo));
}
export function inviteUserInfoFromJSON(
  jsonString: string,
): SafeParseResult<InviteUserInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InviteUserInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InviteUserInfo' from JSON`,
  );
}
