/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OpalAccessQueryResults,
  OpalAccessQueryResults$inboundSchema,
  OpalAccessQueryResults$Outbound,
  OpalAccessQueryResults$outboundSchema,
} from "./opalaccessqueryresults.js";
import {
  OpalNodeQueryResults,
  OpalNodeQueryResults$inboundSchema,
  OpalNodeQueryResults$Outbound,
  OpalNodeQueryResults$outboundSchema,
} from "./opalnodequeryresults.js";

/**
 * Paginated results of an OpalQuery. The `type` field discriminates which result schema applies and mirrors the `type` field on the request.
 */
export type OpalQueryResults = OpalNodeQueryResults | OpalAccessQueryResults;

/** @internal */
export const OpalQueryResults$inboundSchema: z.ZodType<
  OpalQueryResults,
  z.ZodTypeDef,
  unknown
> = z.union([
  OpalNodeQueryResults$inboundSchema,
  OpalAccessQueryResults$inboundSchema,
]);
/** @internal */
export type OpalQueryResults$Outbound =
  | OpalNodeQueryResults$Outbound
  | OpalAccessQueryResults$Outbound;

/** @internal */
export const OpalQueryResults$outboundSchema: z.ZodType<
  OpalQueryResults$Outbound,
  z.ZodTypeDef,
  OpalQueryResults
> = z.union([
  OpalNodeQueryResults$outboundSchema,
  OpalAccessQueryResults$outboundSchema,
]);

export function opalQueryResultsToJSON(
  opalQueryResults: OpalQueryResults,
): string {
  return JSON.stringify(
    OpalQueryResults$outboundSchema.parse(opalQueryResults),
  );
}
export function opalQueryResultsFromJSON(
  jsonString: string,
): SafeParseResult<OpalQueryResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpalQueryResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpalQueryResults' from JSON`,
  );
}
