/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A single access path within an ACCESS result.
 */
export type OpalAccessPathDetail = {
  /**
   * Entity IDs along the path from principal to entitlement.
   */
  path: Array<string>;
  /**
   * This path's expiration, if any.
   */
  expiration?: Date | null | undefined;
};

/** @internal */
export const OpalAccessPathDetail$inboundSchema: z.ZodType<
  OpalAccessPathDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.array(z.string()),
  expiration: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});
/** @internal */
export type OpalAccessPathDetail$Outbound = {
  path: Array<string>;
  expiration?: string | null | undefined;
};

/** @internal */
export const OpalAccessPathDetail$outboundSchema: z.ZodType<
  OpalAccessPathDetail$Outbound,
  z.ZodTypeDef,
  OpalAccessPathDetail
> = z.object({
  path: z.array(z.string()),
  expiration: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});

export function opalAccessPathDetailToJSON(
  opalAccessPathDetail: OpalAccessPathDetail,
): string {
  return JSON.stringify(
    OpalAccessPathDetail$outboundSchema.parse(opalAccessPathDetail),
  );
}
export function opalAccessPathDetailFromJSON(
  jsonString: string,
): SafeParseResult<OpalAccessPathDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpalAccessPathDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpalAccessPathDetail' from JSON`,
  );
}
