/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OpalAccessPathDetail,
  OpalAccessPathDetail$inboundSchema,
  OpalAccessPathDetail$Outbound,
  OpalAccessPathDetail$outboundSchema,
} from "./opalaccesspathdetail.js";

/**
 * A matched access grant from an ACCESS OpalQuery — one per (principal, entitlement, access level), with every access path as metadata.
 */
export type OpalAccessResultNode = {
  /**
   * The principal entity ID.
   */
  principalId: string;
  /**
   * The entitlement entity ID.
   */
  entitlementId: string;
  /**
   * Remote ID of the access level.
   */
  accessLevelRemoteId?: string | null | undefined;
  /**
   * Display name of the access level.
   */
  accessLevelName?: string | null | undefined;
  /**
   * The expiration in effect across all paths (the latest-expiring; a permanent path wins). Null means access never expires.
   */
  effectiveExpiration?: Date | null | undefined;
  /**
   * True when any path is a direct grant.
   */
  isDirect: boolean;
  /**
   * Every access path reaching this grant.
   */
  paths: Array<OpalAccessPathDetail>;
};

/** @internal */
export const OpalAccessResultNode$inboundSchema: z.ZodType<
  OpalAccessResultNode,
  z.ZodTypeDef,
  unknown
> = z.object({
  principalId: z.string(),
  entitlementId: z.string(),
  accessLevelRemoteId: z.nullable(z.string()).optional(),
  accessLevelName: z.nullable(z.string()).optional(),
  effectiveExpiration: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  isDirect: z.boolean(),
  paths: z.array(OpalAccessPathDetail$inboundSchema),
});
/** @internal */
export type OpalAccessResultNode$Outbound = {
  principalId: string;
  entitlementId: string;
  accessLevelRemoteId?: string | null | undefined;
  accessLevelName?: string | null | undefined;
  effectiveExpiration?: string | null | undefined;
  isDirect: boolean;
  paths: Array<OpalAccessPathDetail$Outbound>;
};

/** @internal */
export const OpalAccessResultNode$outboundSchema: z.ZodType<
  OpalAccessResultNode$Outbound,
  z.ZodTypeDef,
  OpalAccessResultNode
> = z.object({
  principalId: z.string(),
  entitlementId: z.string(),
  accessLevelRemoteId: z.nullable(z.string()).optional(),
  accessLevelName: z.nullable(z.string()).optional(),
  effectiveExpiration: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  isDirect: z.boolean(),
  paths: z.array(OpalAccessPathDetail$outboundSchema),
});

export function opalAccessResultNodeToJSON(
  opalAccessResultNode: OpalAccessResultNode,
): string {
  return JSON.stringify(
    OpalAccessResultNode$outboundSchema.parse(opalAccessResultNode),
  );
}
export function opalAccessResultNodeFromJSON(
  jsonString: string,
): SafeParseResult<OpalAccessResultNode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpalAccessResultNode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpalAccessResultNode' from JSON`,
  );
}
