/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OpalAccessPathResultEdge,
  OpalAccessPathResultEdge$inboundSchema,
  OpalAccessPathResultEdge$Outbound,
  OpalAccessPathResultEdge$outboundSchema,
} from "./opalaccesspathresultedge.js";
import {
  PageInfo,
  PageInfo$inboundSchema,
  PageInfo$Outbound,
  PageInfo$outboundSchema,
} from "./pageinfo.js";

/**
 * Paginated results of an ACCESS_PATH-type OpalQuery — one edge per matched principal-to-entitlement access path.
 */
export type OpalAccessPathQueryResults = {
  type: "ACCESS_PATH";
  /**
   * List of matched access paths.
   */
  edges: Array<OpalAccessPathResultEdge>;
  pageInfo: PageInfo;
  /**
   * Exact total number of matching paths when includeCount was true on the request; otherwise null.
   */
  totalCount?: number | null | undefined;
};

/** @internal */
export const OpalAccessPathQueryResults$inboundSchema: z.ZodType<
  OpalAccessPathQueryResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("ACCESS_PATH"),
  edges: z.array(OpalAccessPathResultEdge$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
  totalCount: z.nullable(z.number().int()).optional(),
});
/** @internal */
export type OpalAccessPathQueryResults$Outbound = {
  type: "ACCESS_PATH";
  edges: Array<OpalAccessPathResultEdge$Outbound>;
  pageInfo: PageInfo$Outbound;
  totalCount?: number | null | undefined;
};

/** @internal */
export const OpalAccessPathQueryResults$outboundSchema: z.ZodType<
  OpalAccessPathQueryResults$Outbound,
  z.ZodTypeDef,
  OpalAccessPathQueryResults
> = z.object({
  type: z.literal("ACCESS_PATH"),
  edges: z.array(OpalAccessPathResultEdge$outboundSchema),
  pageInfo: PageInfo$outboundSchema,
  totalCount: z.nullable(z.number().int()).optional(),
});

export function opalAccessPathQueryResultsToJSON(
  opalAccessPathQueryResults: OpalAccessPathQueryResults,
): string {
  return JSON.stringify(
    OpalAccessPathQueryResults$outboundSchema.parse(opalAccessPathQueryResults),
  );
}
export function opalAccessPathQueryResultsFromJSON(
  jsonString: string,
): SafeParseResult<OpalAccessPathQueryResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpalAccessPathQueryResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpalAccessPathQueryResults' from JSON`,
  );
}
