/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OpalQueryResultEdge,
  OpalQueryResultEdge$inboundSchema,
  OpalQueryResultEdge$Outbound,
  OpalQueryResultEdge$outboundSchema,
} from "./opalqueryresultedge.js";
import {
  PageInfo,
  PageInfo$inboundSchema,
  PageInfo$Outbound,
  PageInfo$outboundSchema,
} from "./pageinfo.js";

/**
 * Paginated results of a NODE-type OpalQuery — one edge per matched entity (user, resource, or group).
 */
export type OpalNodeQueryResults = {
  type: "NODE";
  /**
   * List of matched entities.
   */
  edges: Array<OpalQueryResultEdge>;
  pageInfo: PageInfo;
};

/** @internal */
export const OpalNodeQueryResults$inboundSchema: z.ZodType<
  OpalNodeQueryResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("NODE"),
  edges: z.array(OpalQueryResultEdge$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});
/** @internal */
export type OpalNodeQueryResults$Outbound = {
  type: "NODE";
  edges: Array<OpalQueryResultEdge$Outbound>;
  pageInfo: PageInfo$Outbound;
};

/** @internal */
export const OpalNodeQueryResults$outboundSchema: z.ZodType<
  OpalNodeQueryResults$Outbound,
  z.ZodTypeDef,
  OpalNodeQueryResults
> = z.object({
  type: z.literal("NODE"),
  edges: z.array(OpalQueryResultEdge$outboundSchema),
  pageInfo: PageInfo$outboundSchema,
});

export function opalNodeQueryResultsToJSON(
  opalNodeQueryResults: OpalNodeQueryResults,
): string {
  return JSON.stringify(
    OpalNodeQueryResults$outboundSchema.parse(opalNodeQueryResults),
  );
}
export function opalNodeQueryResultsFromJSON(
  jsonString: string,
): SafeParseResult<OpalNodeQueryResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpalNodeQueryResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpalNodeQueryResults' from JSON`,
  );
}
