/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * A connector a Paladin is allowed to use.
 */
export const PaladinConnector = {
  Notion: "NOTION",
  Jira: "JIRA",
  Linear: "LINEAR",
  ServiceNow: "SERVICE_NOW",
  NotionTickets: "NOTION_TICKETS",
  FreshService: "FRESH_SERVICE",
  Shortcut: "SHORTCUT",
  Slack: "SLACK",
  PagerDuty: "PAGER_DUTY",
  Confluence: "CONFLUENCE",
  FleetDm: "FLEET_DM",
} as const;
/**
 * A connector a Paladin is allowed to use.
 */
export type PaladinConnector = ClosedEnum<typeof PaladinConnector>;

/** @internal */
export const PaladinConnector$inboundSchema: z.ZodNativeEnum<
  typeof PaladinConnector
> = z.nativeEnum(PaladinConnector);
/** @internal */
export const PaladinConnector$outboundSchema: z.ZodNativeEnum<
  typeof PaladinConnector
> = PaladinConnector$inboundSchema;
