/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaladinConnector,
  PaladinConnector$inboundSchema,
  PaladinConnector$outboundSchema,
} from "./paladinconnector.js";

/**
 * # Paladin Object
 *
 * @remarks
 * ### Description
 * The `Paladin` object represents a Paladin, Opal's AI access-request
 * reviewer.
 */
export type Paladin = {
  /**
   * The ID of the Paladin. Use this value as a reviewer in a request configuration's service_user_ids.
   */
  paladinId: string;
  /**
   * The name of the Paladin.
   */
  name: string;
  /**
   * The ID of the owner of the Paladin.
   */
  ownerId: string;
  /**
   * When true, the Paladin reasons about requests but takes no action. Shown as "Monitor mode" in the UI.
   */
  monitorMode: boolean;
  /**
   * When true, the Paladin's recommendations are visible only to admins. Only meaningful when monitor_mode is true.
   */
  adminViewOnly: boolean;
  /**
   * The connectors the Paladin is allowed to use.
   */
  enabledConnectors: Array<PaladinConnector>;
  /**
   * The free-form instructions that guide the Paladin's decisions.
   */
  instructions: string;
};

/** @internal */
export const Paladin$inboundSchema: z.ZodType<Paladin, z.ZodTypeDef, unknown> =
  z.object({
    paladin_id: z.string(),
    name: z.string(),
    owner_id: z.string(),
    monitor_mode: z.boolean(),
    admin_view_only: z.boolean(),
    enabled_connectors: z.array(PaladinConnector$inboundSchema),
    instructions: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "paladin_id": "paladinId",
      "owner_id": "ownerId",
      "monitor_mode": "monitorMode",
      "admin_view_only": "adminViewOnly",
      "enabled_connectors": "enabledConnectors",
    });
  });
/** @internal */
export type Paladin$Outbound = {
  paladin_id: string;
  name: string;
  owner_id: string;
  monitor_mode: boolean;
  admin_view_only: boolean;
  enabled_connectors: Array<string>;
  instructions: string;
};

/** @internal */
export const Paladin$outboundSchema: z.ZodType<
  Paladin$Outbound,
  z.ZodTypeDef,
  Paladin
> = z.object({
  paladinId: z.string(),
  name: z.string(),
  ownerId: z.string(),
  monitorMode: z.boolean(),
  adminViewOnly: z.boolean(),
  enabledConnectors: z.array(PaladinConnector$outboundSchema),
  instructions: z.string(),
}).transform((v) => {
  return remap$(v, {
    paladinId: "paladin_id",
    ownerId: "owner_id",
    monitorMode: "monitor_mode",
    adminViewOnly: "admin_view_only",
    enabledConnectors: "enabled_connectors",
  });
});

export function paladinToJSON(paladin: Paladin): string {
  return JSON.stringify(Paladin$outboundSchema.parse(paladin));
}
export function paladinFromJSON(
  jsonString: string,
): SafeParseResult<Paladin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Paladin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Paladin' from JSON`,
  );
}
