/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The decision level for the approval
 */
export const RequestApprovalEnum = {
  Regular: "REGULAR",
  Admin: "ADMIN",
} as const;
/**
 * The decision level for the approval
 */
export type RequestApprovalEnum = ClosedEnum<typeof RequestApprovalEnum>;

/** @internal */
export const RequestApprovalEnum$inboundSchema: z.ZodNativeEnum<
  typeof RequestApprovalEnum
> = z.nativeEnum(RequestApprovalEnum);

/** @internal */
export const RequestApprovalEnum$outboundSchema: z.ZodNativeEnum<
  typeof RequestApprovalEnum
> = RequestApprovalEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestApprovalEnum$ {
  /** @deprecated use `RequestApprovalEnum$inboundSchema` instead. */
  export const inboundSchema = RequestApprovalEnum$inboundSchema;
  /** @deprecated use `RequestApprovalEnum$outboundSchema` instead. */
  export const outboundSchema = RequestApprovalEnum$outboundSchema;
}
