/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * # Request Comment Object
 *
 * @remarks
 * ### Description
 * The `RequestComment` object is used to represent a comment on a request.
 *
 * ### Usage Example
 * Returned from the `GET Requests` endpoint as part of a `Request` object.
 */
export type RequestComment = {
  /**
   * The date and time the comment was created.
   */
  createdAt: Date;
  /**
   * The unique identifier of the request the comment is associated with.
   */
  requestId: string;
  /**
   * The unique identifier of the user who made the comment.
   */
  userId: string;
  /**
   * The user's full name.
   */
  userFullName?: string | undefined;
  /**
   * The user's email address.
   */
  userEmail?: string | undefined;
  /**
   * The content of the comment.
   */
  comment: string;
};

/** @internal */
export const RequestComment$inboundSchema: z.ZodType<
  RequestComment,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  request_id: z.string(),
  user_id: z.string(),
  user_full_name: z.string().optional(),
  user_email: z.string().optional(),
  comment: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "request_id": "requestId",
    "user_id": "userId",
    "user_full_name": "userFullName",
    "user_email": "userEmail",
  });
});
/** @internal */
export type RequestComment$Outbound = {
  created_at: string;
  request_id: string;
  user_id: string;
  user_full_name?: string | undefined;
  user_email?: string | undefined;
  comment: string;
};

/** @internal */
export const RequestComment$outboundSchema: z.ZodType<
  RequestComment$Outbound,
  z.ZodTypeDef,
  RequestComment
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  requestId: z.string(),
  userId: z.string(),
  userFullName: z.string().optional(),
  userEmail: z.string().optional(),
  comment: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    requestId: "request_id",
    userId: "user_id",
    userFullName: "user_full_name",
    userEmail: "user_email",
  });
});

export function requestCommentToJSON(requestComment: RequestComment): string {
  return JSON.stringify(RequestComment$outboundSchema.parse(requestComment));
}
export function requestCommentFromJSON(
  jsonString: string,
): SafeParseResult<RequestComment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequestComment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestComment' from JSON`,
  );
}
