/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RequestTemplateCustomFieldCalloutMetadata,
  RequestTemplateCustomFieldCalloutMetadata$inboundSchema,
  RequestTemplateCustomFieldCalloutMetadata$Outbound,
  RequestTemplateCustomFieldCalloutMetadata$outboundSchema,
} from "./requesttemplatecustomfieldcalloutmetadata.js";
import {
  RequestTemplateCustomFieldMultiChoiceMetadata,
  RequestTemplateCustomFieldMultiChoiceMetadata$inboundSchema,
  RequestTemplateCustomFieldMultiChoiceMetadata$Outbound,
  RequestTemplateCustomFieldMultiChoiceMetadata$outboundSchema,
} from "./requesttemplatecustomfieldmultichoicemetadata.js";

/**
 * Extra configuration for field types that need it. Exactly one member is set, and which one is determined by the field's `type`.
 */
export type RequestTemplateCustomFieldMetadata = {
  /**
   * The message shown to a requester by a `CALLOUT` field, and how prominently to show it.
   */
  calloutData?: RequestTemplateCustomFieldCalloutMetadata | undefined;
  /**
   * The options a requester can pick from in a `MULTI_CHOICE` or `MULTI_SELECT` field.
   */
  multiChoiceData?: RequestTemplateCustomFieldMultiChoiceMetadata | undefined;
};

/** @internal */
export const RequestTemplateCustomFieldMetadata$inboundSchema: z.ZodType<
  RequestTemplateCustomFieldMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  callout_data: RequestTemplateCustomFieldCalloutMetadata$inboundSchema
    .optional(),
  multi_choice_data: RequestTemplateCustomFieldMultiChoiceMetadata$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "callout_data": "calloutData",
    "multi_choice_data": "multiChoiceData",
  });
});
/** @internal */
export type RequestTemplateCustomFieldMetadata$Outbound = {
  callout_data?: RequestTemplateCustomFieldCalloutMetadata$Outbound | undefined;
  multi_choice_data?:
    | RequestTemplateCustomFieldMultiChoiceMetadata$Outbound
    | undefined;
};

/** @internal */
export const RequestTemplateCustomFieldMetadata$outboundSchema: z.ZodType<
  RequestTemplateCustomFieldMetadata$Outbound,
  z.ZodTypeDef,
  RequestTemplateCustomFieldMetadata
> = z.object({
  calloutData: RequestTemplateCustomFieldCalloutMetadata$outboundSchema
    .optional(),
  multiChoiceData: RequestTemplateCustomFieldMultiChoiceMetadata$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    calloutData: "callout_data",
    multiChoiceData: "multi_choice_data",
  });
});

export function requestTemplateCustomFieldMetadataToJSON(
  requestTemplateCustomFieldMetadata: RequestTemplateCustomFieldMetadata,
): string {
  return JSON.stringify(
    RequestTemplateCustomFieldMetadata$outboundSchema.parse(
      requestTemplateCustomFieldMetadata,
    ),
  );
}
export function requestTemplateCustomFieldMetadataFromJSON(
  jsonString: string,
): SafeParseResult<RequestTemplateCustomFieldMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RequestTemplateCustomFieldMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestTemplateCustomFieldMetadata' from JSON`,
  );
}
