/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Information about a resource and corresponding access level
 */
export type ResourceWithAccessLevel = {
  /**
   * The ID of the resource.
   */
  resourceId: string;
  /**
   * The ID of the resource.
   */
  accessLevelRemoteId?: string | undefined;
};

/** @internal */
export const ResourceWithAccessLevel$inboundSchema: z.ZodType<
  ResourceWithAccessLevel,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_id: z.string(),
  access_level_remote_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "resource_id": "resourceId",
    "access_level_remote_id": "accessLevelRemoteId",
  });
});

/** @internal */
export type ResourceWithAccessLevel$Outbound = {
  resource_id: string;
  access_level_remote_id?: string | undefined;
};

/** @internal */
export const ResourceWithAccessLevel$outboundSchema: z.ZodType<
  ResourceWithAccessLevel$Outbound,
  z.ZodTypeDef,
  ResourceWithAccessLevel
> = z.object({
  resourceId: z.string(),
  accessLevelRemoteId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    resourceId: "resource_id",
    accessLevelRemoteId: "access_level_remote_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceWithAccessLevel$ {
  /** @deprecated use `ResourceWithAccessLevel$inboundSchema` instead. */
  export const inboundSchema = ResourceWithAccessLevel$inboundSchema;
  /** @deprecated use `ResourceWithAccessLevel$outboundSchema` instead. */
  export const outboundSchema = ResourceWithAccessLevel$outboundSchema;
  /** @deprecated use `ResourceWithAccessLevel$Outbound` instead. */
  export type Outbound = ResourceWithAccessLevel$Outbound;
}

export function resourceWithAccessLevelToJSON(
  resourceWithAccessLevel: ResourceWithAccessLevel,
): string {
  return JSON.stringify(
    ResourceWithAccessLevel$outboundSchema.parse(resourceWithAccessLevel),
  );
}

export function resourceWithAccessLevelFromJSON(
  jsonString: string,
): SafeParseResult<ResourceWithAccessLevel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceWithAccessLevel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceWithAccessLevel' from JSON`,
  );
}
