/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CampaignItemReviewResult,
  CampaignItemReviewResult$inboundSchema,
  CampaignItemReviewResult$Outbound,
  CampaignItemReviewResult$outboundSchema,
} from "./campaignitemreviewresult.js";

/**
 * Result of submitting campaign item review decisions.
 */
export type ReviewCampaignItemsResponse = {
  /**
   * Updated reviews in the same order as the request decisions.
   */
  reviews: Array<CampaignItemReviewResult>;
};

/** @internal */
export const ReviewCampaignItemsResponse$inboundSchema: z.ZodType<
  ReviewCampaignItemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  reviews: z.array(CampaignItemReviewResult$inboundSchema),
});
/** @internal */
export type ReviewCampaignItemsResponse$Outbound = {
  reviews: Array<CampaignItemReviewResult$Outbound>;
};

/** @internal */
export const ReviewCampaignItemsResponse$outboundSchema: z.ZodType<
  ReviewCampaignItemsResponse$Outbound,
  z.ZodTypeDef,
  ReviewCampaignItemsResponse
> = z.object({
  reviews: z.array(CampaignItemReviewResult$outboundSchema),
});

export function reviewCampaignItemsResponseToJSON(
  reviewCampaignItemsResponse: ReviewCampaignItemsResponse,
): string {
  return JSON.stringify(
    ReviewCampaignItemsResponse$outboundSchema.parse(
      reviewCampaignItemsResponse,
    ),
  );
}
export function reviewCampaignItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReviewCampaignItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReviewCampaignItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReviewCampaignItemsResponse' from JSON`,
  );
}
