/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StopCampaignRequest = {
  /**
   * Revoke all unreviewed access grants. Access grants with no reviewer decision will be immediately revoked.
   */
  revokeUnreviewed?: boolean | undefined;
};

/** @internal */
export const StopCampaignRequest$inboundSchema: z.ZodType<
  StopCampaignRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  revoke_unreviewed: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "revoke_unreviewed": "revokeUnreviewed",
  });
});
/** @internal */
export type StopCampaignRequest$Outbound = {
  revoke_unreviewed: boolean;
};

/** @internal */
export const StopCampaignRequest$outboundSchema: z.ZodType<
  StopCampaignRequest$Outbound,
  z.ZodTypeDef,
  StopCampaignRequest
> = z.object({
  revokeUnreviewed: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    revokeUnreviewed: "revoke_unreviewed",
  });
});

export function stopCampaignRequestToJSON(
  stopCampaignRequest: StopCampaignRequest,
): string {
  return JSON.stringify(
    StopCampaignRequest$outboundSchema.parse(stopCampaignRequest),
  );
}
export function stopCampaignRequestFromJSON(
  jsonString: string,
): SafeParseResult<StopCampaignRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StopCampaignRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StopCampaignRequest' from JSON`,
  );
}
