/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * How to match a string value against entity names. REGEX matches the value as a case-insensitive regular expression.
 */
export const StringMatchType = {
  Contains: "CONTAINS",
  Equals: "EQUALS",
  StartsWith: "STARTS_WITH",
  EndsWith: "ENDS_WITH",
  Regex: "REGEX",
} as const;
/**
 * How to match a string value against entity names. REGEX matches the value as a case-insensitive regular expression.
 */
export type StringMatchType = ClosedEnum<typeof StringMatchType>;

/** @internal */
export const StringMatchType$inboundSchema: z.ZodNativeEnum<
  typeof StringMatchType
> = z.nativeEnum(StringMatchType);
/** @internal */
export const StringMatchType$outboundSchema: z.ZodNativeEnum<
  typeof StringMatchType
> = StringMatchType$inboundSchema;
