/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SyncError,
  SyncError$inboundSchema,
  SyncError$Outbound,
  SyncError$outboundSchema,
} from "./syncerror.js";

export type SyncErrorList = {
  syncErrors: Array<SyncError>;
};

/** @internal */
export const SyncErrorList$inboundSchema: z.ZodType<
  SyncErrorList,
  z.ZodTypeDef,
  unknown
> = z.object({
  sync_errors: z.array(SyncError$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "sync_errors": "syncErrors",
  });
});
/** @internal */
export type SyncErrorList$Outbound = {
  sync_errors: Array<SyncError$Outbound>;
};

/** @internal */
export const SyncErrorList$outboundSchema: z.ZodType<
  SyncErrorList$Outbound,
  z.ZodTypeDef,
  SyncErrorList
> = z.object({
  syncErrors: z.array(SyncError$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    syncErrors: "sync_errors",
  });
});

export function syncErrorListToJSON(syncErrorList: SyncErrorList): string {
  return JSON.stringify(SyncErrorList$outboundSchema.parse(syncErrorList));
}
export function syncErrorListFromJSON(
  jsonString: string,
): SafeParseResult<SyncErrorList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncErrorList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncErrorList' from JSON`,
  );
}
