/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * A policy for auto-assigning reviewers. If auto-assignment is on, specific assignments can still be manually adjusted after the access review is started. Default is Manually.
 */
export const UARReviewerAssignmentPolicyEnum = {
  Manually: "MANUALLY",
  ByOwningTeamAdmin: "BY_OWNING_TEAM_ADMIN",
  ByManager: "BY_MANAGER",
} as const;
/**
 * A policy for auto-assigning reviewers. If auto-assignment is on, specific assignments can still be manually adjusted after the access review is started. Default is Manually.
 */
export type UARReviewerAssignmentPolicyEnum = ClosedEnum<
  typeof UARReviewerAssignmentPolicyEnum
>;

/** @internal */
export const UARReviewerAssignmentPolicyEnum$inboundSchema: z.ZodNativeEnum<
  typeof UARReviewerAssignmentPolicyEnum
> = z.nativeEnum(UARReviewerAssignmentPolicyEnum);

/** @internal */
export const UARReviewerAssignmentPolicyEnum$outboundSchema: z.ZodNativeEnum<
  typeof UARReviewerAssignmentPolicyEnum
> = UARReviewerAssignmentPolicyEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UARReviewerAssignmentPolicyEnum$ {
  /** @deprecated use `UARReviewerAssignmentPolicyEnum$inboundSchema` instead. */
  export const inboundSchema = UARReviewerAssignmentPolicyEnum$inboundSchema;
  /** @deprecated use `UARReviewerAssignmentPolicyEnum$outboundSchema` instead. */
  export const outboundSchema = UARReviewerAssignmentPolicyEnum$outboundSchema;
}
