/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CampaignItemReview,
  CampaignItemReview$inboundSchema,
  CampaignItemReview$Outbound,
  CampaignItemReview$outboundSchema,
} from "./campaignitemreview.js";
import {
  CampaignItemUnassignedPresetMessage,
  CampaignItemUnassignedPresetMessage$inboundSchema,
  CampaignItemUnassignedPresetMessage$Outbound,
  CampaignItemUnassignedPresetMessage$outboundSchema,
} from "./campaignitemunassignedpresetmessage.js";

/**
 * Result of updating campaign item reviewers.
 */
export type UpdateCampaignItemReviewersResult = {
  /**
   * Full review set for every referenced item after the update.
   */
  reviews: Array<CampaignItemReview>;
  /**
   * Preset assignment messages for items that did not produce a review row.
   */
  unassignedPresetMessages: Array<CampaignItemUnassignedPresetMessage>;
};

/** @internal */
export const UpdateCampaignItemReviewersResult$inboundSchema: z.ZodType<
  UpdateCampaignItemReviewersResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  reviews: z.array(CampaignItemReview$inboundSchema),
  unassigned_preset_messages: z.array(
    CampaignItemUnassignedPresetMessage$inboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    "unassigned_preset_messages": "unassignedPresetMessages",
  });
});
/** @internal */
export type UpdateCampaignItemReviewersResult$Outbound = {
  reviews: Array<CampaignItemReview$Outbound>;
  unassigned_preset_messages: Array<
    CampaignItemUnassignedPresetMessage$Outbound
  >;
};

/** @internal */
export const UpdateCampaignItemReviewersResult$outboundSchema: z.ZodType<
  UpdateCampaignItemReviewersResult$Outbound,
  z.ZodTypeDef,
  UpdateCampaignItemReviewersResult
> = z.object({
  reviews: z.array(CampaignItemReview$outboundSchema),
  unassignedPresetMessages: z.array(
    CampaignItemUnassignedPresetMessage$outboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    unassignedPresetMessages: "unassigned_preset_messages",
  });
});

export function updateCampaignItemReviewersResultToJSON(
  updateCampaignItemReviewersResult: UpdateCampaignItemReviewersResult,
): string {
  return JSON.stringify(
    UpdateCampaignItemReviewersResult$outboundSchema.parse(
      updateCampaignItemReviewersResult,
    ),
  );
}
export function updateCampaignItemReviewersResultFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCampaignItemReviewersResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCampaignItemReviewersResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCampaignItemReviewersResult' from JSON`,
  );
}
