/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Info for updating a custom access level.
 */
export type UpdateResourceCustomAccessLevelInfo = {
  /**
   * The new human-readable name.
   */
  accessLevelName?: string | undefined;
  /**
   * The new policy document.
   */
  policy?: string | null | undefined;
  /**
   * Whether the role is requestable.
   */
  requestableByDefault?: boolean | undefined;
  /**
   * The new sensitivity index.
   */
  stackableSensitivityIndex?: number | null | undefined;
  /**
   * Set to true to remove from the hierarchy.
   */
  clearStackableSensitivityIndex?: boolean | undefined;
};

/** @internal */
export const UpdateResourceCustomAccessLevelInfo$inboundSchema: z.ZodType<
  UpdateResourceCustomAccessLevelInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_level_name: z.string().optional(),
  policy: z.nullable(z.string()).optional(),
  requestable_by_default: z.boolean().optional(),
  stackable_sensitivity_index: z.nullable(z.number().int()).optional(),
  clear_stackable_sensitivity_index: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "access_level_name": "accessLevelName",
    "requestable_by_default": "requestableByDefault",
    "stackable_sensitivity_index": "stackableSensitivityIndex",
    "clear_stackable_sensitivity_index": "clearStackableSensitivityIndex",
  });
});
/** @internal */
export type UpdateResourceCustomAccessLevelInfo$Outbound = {
  access_level_name?: string | undefined;
  policy?: string | null | undefined;
  requestable_by_default?: boolean | undefined;
  stackable_sensitivity_index?: number | null | undefined;
  clear_stackable_sensitivity_index?: boolean | undefined;
};

/** @internal */
export const UpdateResourceCustomAccessLevelInfo$outboundSchema: z.ZodType<
  UpdateResourceCustomAccessLevelInfo$Outbound,
  z.ZodTypeDef,
  UpdateResourceCustomAccessLevelInfo
> = z.object({
  accessLevelName: z.string().optional(),
  policy: z.nullable(z.string()).optional(),
  requestableByDefault: z.boolean().optional(),
  stackableSensitivityIndex: z.nullable(z.number().int()).optional(),
  clearStackableSensitivityIndex: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    accessLevelName: "access_level_name",
    requestableByDefault: "requestable_by_default",
    stackableSensitivityIndex: "stackable_sensitivity_index",
    clearStackableSensitivityIndex: "clear_stackable_sensitivity_index",
  });
});

export function updateResourceCustomAccessLevelInfoToJSON(
  updateResourceCustomAccessLevelInfo: UpdateResourceCustomAccessLevelInfo,
): string {
  return JSON.stringify(
    UpdateResourceCustomAccessLevelInfo$outboundSchema.parse(
      updateResourceCustomAccessLevelInfo,
    ),
  );
}
export function updateResourceCustomAccessLevelInfoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateResourceCustomAccessLevelInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateResourceCustomAccessLevelInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateResourceCustomAccessLevelInfo' from JSON`,
  );
}
