/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UpdateCampaignConfigurationInfo,
  UpdateCampaignConfigurationInfo$inboundSchema,
  UpdateCampaignConfigurationInfo$Outbound,
  UpdateCampaignConfigurationInfo$outboundSchema,
} from "./updatecampaignconfigurationinfo.js";

/**
 * # UpdateCampaignInfo Object
 *
 * @remarks
 * ### Description
 * The `UpdateCampaignInfo` object is used to partially update a campaign.
 * Omitted fields are left unchanged.
 *
 * ### Usage Example
 * Use in the `PUT Campaign` endpoint.
 */
export type UpdateCampaignInfo = {
  /**
   * The name of the campaign.
   */
  name?: string | undefined;
  /**
   * Configuration fields to create or update.
   */
  configuration?: UpdateCampaignConfigurationInfo | undefined;
};

/** @internal */
export const UpdateCampaignInfo$inboundSchema: z.ZodType<
  UpdateCampaignInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  configuration: UpdateCampaignConfigurationInfo$inboundSchema.optional(),
});
/** @internal */
export type UpdateCampaignInfo$Outbound = {
  name?: string | undefined;
  configuration?: UpdateCampaignConfigurationInfo$Outbound | undefined;
};

/** @internal */
export const UpdateCampaignInfo$outboundSchema: z.ZodType<
  UpdateCampaignInfo$Outbound,
  z.ZodTypeDef,
  UpdateCampaignInfo
> = z.object({
  name: z.string().optional(),
  configuration: UpdateCampaignConfigurationInfo$outboundSchema.optional(),
});

export function updateCampaignInfoToJSON(
  updateCampaignInfo: UpdateCampaignInfo,
): string {
  return JSON.stringify(
    UpdateCampaignInfo$outboundSchema.parse(updateCampaignInfo),
  );
}
export function updateCampaignInfoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCampaignInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCampaignInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCampaignInfo' from JSON`,
  );
}
