/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaladinConnector,
  PaladinConnector$inboundSchema,
  PaladinConnector$outboundSchema,
} from "./paladinconnector.js";

/**
 * Information for updating a Paladin.
 */
export type UpdatePaladinInfo = {
  /**
   * The name of the Paladin.
   */
  name: string;
  /**
   * When true, the Paladin reasons about requests but takes no action. If omitted, the existing value is preserved.
   */
  monitorMode?: boolean | undefined;
  /**
   * When true, recommendations are visible only to admins. Only meaningful when monitor_mode is true. If omitted, the existing value is preserved.
   */
  adminViewOnly?: boolean | undefined;
  /**
   * The connectors the Paladin is allowed to use. If omitted, the existing connectors are preserved.
   */
  enabledConnectors?: Array<PaladinConnector> | undefined;
  /**
   * The free-form instructions that guide the Paladin's decisions. If omitted, the existing instructions are preserved.
   */
  instructions?: string | undefined;
};

/** @internal */
export const UpdatePaladinInfo$inboundSchema: z.ZodType<
  UpdatePaladinInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  monitor_mode: z.boolean().optional(),
  admin_view_only: z.boolean().optional(),
  enabled_connectors: z.array(PaladinConnector$inboundSchema).optional(),
  instructions: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "monitor_mode": "monitorMode",
    "admin_view_only": "adminViewOnly",
    "enabled_connectors": "enabledConnectors",
  });
});
/** @internal */
export type UpdatePaladinInfo$Outbound = {
  name: string;
  monitor_mode?: boolean | undefined;
  admin_view_only?: boolean | undefined;
  enabled_connectors?: Array<string> | undefined;
  instructions?: string | undefined;
};

/** @internal */
export const UpdatePaladinInfo$outboundSchema: z.ZodType<
  UpdatePaladinInfo$Outbound,
  z.ZodTypeDef,
  UpdatePaladinInfo
> = z.object({
  name: z.string(),
  monitorMode: z.boolean().optional(),
  adminViewOnly: z.boolean().optional(),
  enabledConnectors: z.array(PaladinConnector$outboundSchema).optional(),
  instructions: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    monitorMode: "monitor_mode",
    adminViewOnly: "admin_view_only",
    enabledConnectors: "enabled_connectors",
  });
});

export function updatePaladinInfoToJSON(
  updatePaladinInfo: UpdatePaladinInfo,
): string {
  return JSON.stringify(
    UpdatePaladinInfo$outboundSchema.parse(updatePaladinInfo),
  );
}
export function updatePaladinInfoFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePaladinInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePaladinInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePaladinInfo' from JSON`,
  );
}
