/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RequestTemplateCustomFieldInput,
  RequestTemplateCustomFieldInput$inboundSchema,
  RequestTemplateCustomFieldInput$Outbound,
  RequestTemplateCustomFieldInput$outboundSchema,
} from "./requesttemplatecustomfieldinput.js";

/**
 * Information for updating a request template. Omitted properties are left unchanged, but `custom_fields` replaces the template's fields wholesale when provided.
 */
export type UpdateRequestTemplateInfo = {
  /**
   * The ID of the request template to update.
   */
  requestTemplateId: string;
  /**
   * The new name of the request template.
   */
  name?: string | undefined;
  /**
   * The complete set of fields for the template. Any field not included is removed.
   */
  customFields?: Array<RequestTemplateCustomFieldInput> | undefined;
};

/** @internal */
export const UpdateRequestTemplateInfo$inboundSchema: z.ZodType<
  UpdateRequestTemplateInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_template_id: z.string(),
  name: z.string().optional(),
  custom_fields: z.array(RequestTemplateCustomFieldInput$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "request_template_id": "requestTemplateId",
    "custom_fields": "customFields",
  });
});
/** @internal */
export type UpdateRequestTemplateInfo$Outbound = {
  request_template_id: string;
  name?: string | undefined;
  custom_fields?: Array<RequestTemplateCustomFieldInput$Outbound> | undefined;
};

/** @internal */
export const UpdateRequestTemplateInfo$outboundSchema: z.ZodType<
  UpdateRequestTemplateInfo$Outbound,
  z.ZodTypeDef,
  UpdateRequestTemplateInfo
> = z.object({
  requestTemplateId: z.string(),
  name: z.string().optional(),
  customFields: z.array(RequestTemplateCustomFieldInput$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestTemplateId: "request_template_id",
    customFields: "custom_fields",
  });
});

export function updateRequestTemplateInfoToJSON(
  updateRequestTemplateInfo: UpdateRequestTemplateInfo,
): string {
  return JSON.stringify(
    UpdateRequestTemplateInfo$outboundSchema.parse(updateRequestTemplateInfo),
  );
}
export function updateRequestTemplateInfoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateRequestTemplateInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateRequestTemplateInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateRequestTemplateInfo' from JSON`,
  );
}
