/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Information needed to update a Custom Connector app. Omitted fields are
 *
 * @remarks
 * left unchanged. Provide `signing_secret` only when rotating the secret.
 */
export type UpdateCustomConnectorInfo = {
  /**
   * The identifier of the Custom Connector.
   */
  identifier?: string | undefined;
  /**
   * The base URL of the Custom Connector.
   */
  baseUrl?: string | undefined;
  /**
   * New signing secret. Write-only; never returned by the API. Omit to
   *
   * @remarks
   * leave the existing secret unchanged.
   */
  signingSecret?: string | undefined;
  /**
   * Whether TLS verification is enabled for the Custom Connector.
   */
  tlsMode?: boolean | undefined;
  /**
   * Optional PEM-encoded CA certificate content for TLS.
   */
  tlsCaCertContent?: string | null | undefined;
  /**
   * Whether the Custom Connector supports groups.
   */
  supportsGroups?: boolean | undefined;
  /**
   * Whether the Custom Connector supports nested resources.
   */
  supportsNestedResources?: boolean | undefined;
  /**
   * Whether the Custom Connector supports nested groups.
   */
  supportsNestedGroups?: boolean | undefined;
  /**
   * Whether the Custom Connector supports event ingestion.
   */
  supportsEventIngestion?: boolean | undefined;
};

/** @internal */
export const UpdateCustomConnectorInfo$inboundSchema: z.ZodType<
  UpdateCustomConnectorInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string().optional(),
  base_url: z.string().optional(),
  signing_secret: z.string().optional(),
  tls_mode: z.boolean().optional(),
  tls_ca_cert_content: z.nullable(z.string()).optional(),
  supports_groups: z.boolean().optional(),
  supports_nested_resources: z.boolean().optional(),
  supports_nested_groups: z.boolean().optional(),
  supports_event_ingestion: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "base_url": "baseUrl",
    "signing_secret": "signingSecret",
    "tls_mode": "tlsMode",
    "tls_ca_cert_content": "tlsCaCertContent",
    "supports_groups": "supportsGroups",
    "supports_nested_resources": "supportsNestedResources",
    "supports_nested_groups": "supportsNestedGroups",
    "supports_event_ingestion": "supportsEventIngestion",
  });
});
/** @internal */
export type UpdateCustomConnectorInfo$Outbound = {
  identifier?: string | undefined;
  base_url?: string | undefined;
  signing_secret?: string | undefined;
  tls_mode?: boolean | undefined;
  tls_ca_cert_content?: string | null | undefined;
  supports_groups?: boolean | undefined;
  supports_nested_resources?: boolean | undefined;
  supports_nested_groups?: boolean | undefined;
  supports_event_ingestion?: boolean | undefined;
};

/** @internal */
export const UpdateCustomConnectorInfo$outboundSchema: z.ZodType<
  UpdateCustomConnectorInfo$Outbound,
  z.ZodTypeDef,
  UpdateCustomConnectorInfo
> = z.object({
  identifier: z.string().optional(),
  baseUrl: z.string().optional(),
  signingSecret: z.string().optional(),
  tlsMode: z.boolean().optional(),
  tlsCaCertContent: z.nullable(z.string()).optional(),
  supportsGroups: z.boolean().optional(),
  supportsNestedResources: z.boolean().optional(),
  supportsNestedGroups: z.boolean().optional(),
  supportsEventIngestion: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    baseUrl: "base_url",
    signingSecret: "signing_secret",
    tlsMode: "tls_mode",
    tlsCaCertContent: "tls_ca_cert_content",
    supportsGroups: "supports_groups",
    supportsNestedResources: "supports_nested_resources",
    supportsNestedGroups: "supports_nested_groups",
    supportsEventIngestion: "supports_event_ingestion",
  });
});

export function updateCustomConnectorInfoToJSON(
  updateCustomConnectorInfo: UpdateCustomConnectorInfo,
): string {
  return JSON.stringify(
    UpdateCustomConnectorInfo$outboundSchema.parse(updateCustomConnectorInfo),
  );
}
export function updateCustomConnectorInfoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCustomConnectorInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCustomConnectorInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCustomConnectorInfo' from JSON`,
  );
}
