/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A list of user IDs.
 */
export type UserIDList = {
  userIds: Array<string>;
};

/** @internal */
export const UserIDList$inboundSchema: z.ZodType<
  UserIDList,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_ids: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "user_ids": "userIds",
  });
});
/** @internal */
export type UserIDList$Outbound = {
  user_ids: Array<string>;
};

/** @internal */
export const UserIDList$outboundSchema: z.ZodType<
  UserIDList$Outbound,
  z.ZodTypeDef,
  UserIDList
> = z.object({
  userIds: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    userIds: "user_ids",
  });
});

export function userIDListToJSON(userIDList: UserIDList): string {
  return JSON.stringify(UserIDList$outboundSchema.parse(userIDList));
}
export function userIDListFromJSON(
  jsonString: string,
): SafeParseResult<UserIDList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserIDList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserIDList' from JSON`,
  );
}
