/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The authentication type for webhook connections.
 */
export const WebhookAuthTypeEnum = {
  None: "NONE",
  ApiKey: "API_KEY",
  Hmac: "HMAC",
} as const;
/**
 * The authentication type for webhook connections.
 */
export type WebhookAuthTypeEnum = ClosedEnum<typeof WebhookAuthTypeEnum>;

/** @internal */
export const WebhookAuthTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof WebhookAuthTypeEnum
> = z.nativeEnum(WebhookAuthTypeEnum);
/** @internal */
export const WebhookAuthTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof WebhookAuthTypeEnum
> = WebhookAuthTypeEnum$inboundSchema;
